Sapphire: src/Setup.cpp File Reference
Setup.cpp File Reference
#include "NuclearMass.h"
#include "GammaTransmissionFunc.h"
#include "NuclearLevels.h"
#include "Decayer.h"
#include "Sapphire_config.h"
#include "TransitionRateFunc.h"
#include "CrossSection.h"
#include "PreEqDecayer.h"
#include "ParticleTransmissionFunc.h"
#include "CoulFunc.h"
#include <iostream>
#include <gsl/gsl_errno.h>
Functions
void Initialize ()
Function Documentation
void Initialize ()
... text ...
References CrossSection::CreateMACSEnergiesVector(), CrossSection::CreateTempVector(), CoulFunc::GSLErrorHandler(), NuclearMass::InitializeElements(), GammaTransmissionFunc::InitializeGDRParameters(), NuclearLevels::InitializeLevels(), NuclearMass::InitializeMasses(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), Decayer::SetCrossSection(), PreEqDecayer::SetCrossSection(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), Decayer::SetMaxL(), PreEqDecayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), and CrossSection::SetResidualProton().
Referenced by main().