Sapphire: CrossSection Class Reference
CrossSection Class Reference
#include <CrossSection.h>
Public Member Functions
CrossSection (int Z, int A, int pType, std::string energyFile, bool forRates, int entranceState=0, std::vector< int > exitStates=std::vector< int >(4,-1))
The original constructor of the CrossSection class.
CrossSection (SapphireInput &input)
Constructor on the basis of a SapphireInput object.
bool IsValid () const
void Calculate ()
void PrintCrossSections ()
void PrintTransmissionTerms ()
std::pair< double, double > CalcAverageSWaveResWidth ()
std::pair< double, double > CalcAveragePWaveResWidth ()
std::pair< double, double > CalcAverageDWaveResWidth ()
void CalculateReactionRates (bool)
void PrintReactionRates (bool)
Static Public Member Functions
static void SetResidualGamma (bool residual)
static void SetResidualNeutron (bool residual)
static void SetResidualProton (bool residual)
static void SetResidualAlpha (bool residual)
static void SetCalculateGammaCutoff (bool calc)
static void CreateTempVector ()
static void CreateMACSEnergiesVector ()
Private Member Functions
bool FillEnergies (std::string energyFile)
Read in the energyFile and push back the energies to the CrossSection::crossSections_.
bool CalcAllowedJPi (bool calcRates)
Method to fill the std::vector<std::pair<double,int> > allowedJPi_.
bool CalcDecayerVector (double, DecayerVector &, bool forAverageWidth=false)
void CheckChannels ()
Method to quickly check if the decay into the given exitChannels is energetically allowed.
bool FindInitialState ()
Method to find the attributes of the entrance state and pass them to private member variables by reference.
bool PreSetCompound ()
Method to find the compound mass, charge and preFactor and writes it into the member variables.
void InitializeSeperationEnergies ()
void CalculateEnergyGrid ()
void CalcPartitionFunc ()
Calculation of the normalized partition function of the nucleus as a function of temperatur. The goal of this method is to calculate the partition function of the nucleus as a function of temperature. The temperatures are obtained by the two std::vectors rateTemps_ and macsEnergies_. The normalized partition function is defined as
\[ G_0 = \frac{G(T)}{g_0} = \frac{1}{g_0} \left[ \sum_{\mu} g_{\mu} e^{-\frac{E^x_{\mu}}{kT}} + \int_{E^x_{\mu last}}^\infty \sum_{J, \pi} g_J e^{-\frac{\epsilon}{kT} \rho(\epsilon,J,\pi)} d\epsilon \right]. \]
The first part is a simple sum over the boltzmann factors for degenerated states of the known levels of the nucleus. The second part is the continuum extension using an integration over a level density. At the moment the RauscherLevelDensity is used for this.
Private Attributes
bool gammaCutoffSet_
bool isValid_
bool energiesGiven_
bool calcRates_
bool verbose_ =true
int Z_
int A_
int pType_
int compoundA_
int compoundZ_
int groundStatePi_
int entranceState_
double preFactor_
double groundStateJ_
double seperationEnergy_
double skipEnergy_
double qValue_
std::vector< int > exitStates_
std::vector< double > specifiedExitSepE_
std::vector< double > specifiedExitJ_
std::vector< int > specifiedExitPi_
std::vector< bool > skipped_
std::vector< std::pair< double, int > > allowedJPi_
std::vector< std::pair< double, CrossSectionValues > > crossSections_
std::vector< std::pair< double, CrossSectionValues > > reactionRates_
std::map< int, std::vector< double > > entranceTrans_
std::map< int, std::vector< double > > gExitTrans_
std::map< int, std::vector< double > > nExitTrans_
std::map< int, std::vector< double > > pExitTrans_
std::map< int, std::vector< double > > aExitTrans_
std::vector< std::pair< double, double > > partFunc_
std::vector< std::pair< double, double > > partFuncMACS_
Static Private Attributes
static bool residualGamma_
static bool residualNeutron_
static bool residualProton_
static bool residualAlpha_
static bool calculateGammaCutoff_
static constexpr double minEnergy_ = 0.001
static constexpr double maxEnergy_ = 15.0
static constexpr double dE_ = .1
static std::vector< double > rateTemps_
static std::vector< double > macsEnergies_
Constructor & Destructor Documentation
CrossSection() [1/2]
CrossSection::CrossSection (int Z, int A, int pType, std::string energyFile, bool forRates, int entranceState = 0, std::vector< int > exitStates = std::vector<int>(4,-1))
The original constructor of the CrossSection class.
Parameters
Z Atomic number of the target nucleus.
A Mass number of the target nucleus.
pType Integer indicating the projectile type
energyFile The path to a file containing energies, or ""
forRates A boolean indicating whether rates should be calculated or not.
entranceState The number of the initial state, e.g. 0 = groundstate
exitStates Std::vector<int> which contains the number of levels for which partial cross section should be calculated.
The constructor is responsible to setting up all internal variables needed for the calculation of cross sections. The following steps will be taken:
FindInitialState() will be called, which finds the entrance state in the list of known levels and stores the properties of spin and parity of this state into private member variables (CrossSection::groundstateJ_ and groundstatePi_).
Then the method InitializeSeperationEnergies() will be called which initializes the seperationEnergy_ as well as the properties of the exitStates.
The validity of the exitStates will be checked via CheckChannels().
If the input parameter was set to calculate reaction rates, then the normalized partition function \(G_0(T) = \frac{G(T)}{g_0} \) will be calculated via CalcPartitionFunc().
CalcAllowedJPi() is called to fill the std::vector allowedJPi_ with all allowed combinations of spin and parity for compoundstates accessible via the selection rules. Additionally, maps for the transmission coefficients are initialized.
References CalcAllowedJPi(), CalcPartitionFunc(), CalculateEnergyGrid(), CheckChannels(), crossSections_, dE_, energiesGiven_, FillEnergies(), FindInitialState(), InitializeSeperationEnergies(), isValid_, maxEnergy_, minEnergy_, PreSetCompound(), pType_, and seperationEnergy_.
CrossSection() [2/2]
CrossSection::CrossSection (SapphireInput & input)
Constructor on the basis of a SapphireInput object.
Parameters
input SapphireInput object which needs to be initialized in Module_CrossSection
See CrossSection().
References CalcAllowedJPi(), CalcPartitionFunc(), calcRates_, CalculateEnergyGrid(), CheckChannels(), crossSections_, dE_, energiesGiven_, SapphireInput::EnergyFile(), FillEnergies(), FindInitialState(), InitializeSeperationEnergies(), isValid_, maxEnergy_, minEnergy_, pType_, and seperationEnergy_.
Member Function Documentation
CalcAllowedJPi()
bool CrossSection::CalcAllowedJPi (bool calcRates) private
Method to fill the std::vector<std::pair<double,int> > allowedJPi_.
Parameters
calcRates True or false depending, if rates should be calculated or not.
Returns
True if the size of allowedJPi_ is larger than 0; False otherwise.
Depending on spin selection rules, the vector allowedJP_ is filled under consideration of the target nucleus and the projectile. Additionally, the vectors for the maps:
entranceTrans_
gExitTrans_
nExitTrans_
pExitTrans_
aExitTrans_ are initialized using the size of allowedJPi_
References A_, aExitTrans_, allowedJPi_, entranceTrans_, gExitTrans_, groundStateJ_, groundStatePi_, Decayer::maxL_, nExitTrans_, pExitTrans_, pType_, and verbose_.
Referenced by CrossSection().
CalcAverageDWaveResWidth()
std::pair< double, double > CrossSection::CalcAverageDWaveResWidth ()
References CalcDecayerVector(), compoundA_, compoundZ_, groundStateJ_, groundStatePi_, Decayer::jInitial_, pi, Decayer::piInitial_, seperationEnergy_, Decayer::spinRatePairs_, and Decayer::widthCorrectedDecayer_.
Referenced by Module_OldSapphire::oldSapphire().
CalcAveragePWaveResWidth()
std::pair< double, double > CrossSection::CalcAveragePWaveResWidth ()
References CalcDecayerVector(), compoundA_, compoundZ_, groundStateJ_, groundStatePi_, Decayer::jInitial_, pi, Decayer::piInitial_, seperationEnergy_, Decayer::spinRatePairs_, and Decayer::widthCorrectedDecayer_.
Referenced by Module_OldSapphire::oldSapphire().
CalcAverageSWaveResWidth()
std::pair< double, double > CrossSection::CalcAverageSWaveResWidth ()
References CalcDecayerVector(), compoundA_, compoundZ_, groundStateJ_, groundStatePi_, Decayer::jInitial_, pi, Decayer::piInitial_, seperationEnergy_, Decayer::spinRatePairs_, and Decayer::widthCorrectedDecayer_.
Referenced by Module_OldSapphire::oldSapphire().
CalcDecayerVector()
bool CrossSection::CalcDecayerVector (double E, DecayerVector & decayerVector, bool forAverageWidth = false) private
References A_, allowedJPi_, compoundA_, compoundZ_, Decayer::CorrectWidthFluctuations(), groundStateJ_, groundStatePi_, Decayer::spinRatePairs_, Decayer::widthCorrectedDecayer_, and Z_.
Referenced by CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), and Calculate().
CalcPartitionFunc()
void CrossSection::CalcPartitionFunc () private
Calculation of the normalized partition function of the nucleus as a function of temperatur. The goal of this method is to calculate the partition function of the nucleus as a function of temperature. The temperatures are obtained by the two std::vectors rateTemps_ and macsEnergies_. The normalized partition function is defined as
\[ G_0 = \frac{G(T)}{g_0} = \frac{1}{g_0} \left[ \sum_{\mu} g_{\mu} e^{-\frac{E^x_{\mu}}{kT}} + \int_{E^x_{\mu last}}^\infty \sum_{J, \pi} g_J e^{-\frac{\epsilon}{kT} \rho(\epsilon,J,\pi)} d\epsilon \right]. \]
The first part is a simple sum over the boltzmann factors for degenerated states of the known levels of the nucleus. The second part is the continuum extension using an integration over a level density. At the moment the RauscherLevelDensity is used for this.
More information can be found in, e.g.,:
T. Rauscher, The path to improved reaction rates for astrophysics, Internation Journal of Modern Physics E 20 (2011) 1071. DOI:10.1142/S021830131101840X.
C. Iliadis, Nuclear Physics of Stars, WILEY-VCG Verlag GmbH & Co. KGaA, 2007, ISBN: 978-3-527-40602-9.
For the numerical integration the GNU Scientific Library is used. Information about the integration method can be found here: Numerical Integration with GSL
References A_, boltzConst, NuclearLevels::FindLevels(), groundStateJ_, gsl_partfunc_integrand(), macsEnergies_, partFunc_, partFuncMACS_, rateTemps_, gsl_partfunc_params::temperature, and Z_.
Referenced by CrossSection().
Calculate()
void CrossSection::Calculate ()
References aExitTrans_, CalcDecayerVector(), calculateGammaCutoff_, compoundA_, compoundZ_, crossSections_, energiesGiven_, entranceState_, entranceTrans_, exitStates_, gammaCutoffSet_, gExitTrans_, Decayer::jInitial_, nExitTrans_, pExitTrans_, preFactor_, pType_, residualAlpha_, residualGamma_, residualNeutron_, residualProton_, seperationEnergy_, TransitionRateFunc::SetGammaCutoffEnergy(), skipEnergy_, skipped_, specifiedExitJ_, specifiedExitPi_, specifiedExitSepE_, Decayer::spinRatePairs_, Decayer::totalIntegral_, verbose_, and Decayer::widthCorrectedDecayer_.
Referenced by Module_OldSapphire::oldSapphire(), Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
CalculateEnergyGrid()
void CrossSection::CalculateEnergyGrid () private
References compoundA_, compoundZ_, crossSections_, NuclearLevels::FindLevels(), isValid_, Decayer::maxL_, pType_, NuclearMass::QValue(), rateTemps_, seperationEnergy_, skipEnergy_, and verbose_.
Referenced by CrossSection().
CalculateReactionRates()
void CrossSection::CalculateReactionRates (bool macs)
References avagadroNum, boltzConst, compoundA_, crossSections_, gsl_reactionrate_integrand(), lightSpeedInCmPerS, macsEnergies_, pi, pType_, rateTemps_, reactionRates_, skipped_, and uconv.
Referenced by Module_OldSapphire::oldSapphire().
CheckChannels()
void CrossSection::CheckChannels () private
Method to quickly check if the decay into the given exitChannels is energetically allowed.
References compoundA_, compoundZ_, exitStates_, NuclearLevels::FindLevels(), NuclearMass::QValue(), specifiedExitJ_, specifiedExitPi_, specifiedExitSepE_, and verbose_.
Referenced by CrossSection().
CreateMACSEnergiesVector()
void CrossSection::CreateMACSEnergiesVector () static
References macsEnergies_.
Referenced by Initialize().
CreateTempVector()
void CrossSection::CreateTempVector () static
References rateTemps_.
Referenced by Initialize().
FillEnergies()
bool CrossSection::FillEnergies (std::string energyFile) private
Read in the energyFile and push back the energies to the CrossSection::crossSections_.
Parameters
energyFile std::string containing the path to the energyFile
Returns
true or false depending, if the energies can be read or not
References crossSections_, energiesGiven_, and verbose_.
Referenced by CrossSection().
FindInitialState()
bool CrossSection::FindInitialState () private
Method to find the attributes of the entrance state and pass them to private member variables by reference.
The known levels of the target nucleus are obtained from NuclearLeves::FindLevels() using CrossSection::Z_ and CrossSection::A_ and stored into a std::vector<Level> knonLevels. If the size of the known levels is larger than the number of CrossSection::entranceState_, then the properties (spin and parity) are stored in CrossSection::groundStateJ_ and CrossSection::groundStatePi_. If the initial state cannot be found in the known levelscheme, the function returns false, otherwise true.
Returns
True or false depending on if the initial state is known or not.
The groundState is set to -1.
The levels of the target nucleus are read via the NuclearLevels::FindLevels() method into a std::vector<Level>
References A_, Level::energy_, entranceState_, NuclearLevels::FindLevels(), groundStateJ_, groundStatePi_, isValid_, Level::J_, Level::Pi_, and Z_.
Referenced by CrossSection().
InitializeSeperationEnergies()
void CrossSection::InitializeSeperationEnergies () private
The levels of the target nucleus are read via the NuclearLevels::FindLevels() method into a std::vector<Level>
References A_, entranceState_, NuclearLevels::FindLevels(), qValue_, seperationEnergy_, specifiedExitJ_, specifiedExitPi_, specifiedExitSepE_, verbose_, and Z_.
Referenced by CrossSection().
IsValid()
bool CrossSection::IsValid () const inline
Referenced by Module_OldSapphire::oldSapphire(), Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
PreSetCompound()
bool CrossSection::PreSetCompound () private
Method to find the compound mass, charge and preFactor and writes it into the member variables.
This method is responsible to setting the mass and charge number of the compund nucleus for different projectiles. Moreover, it calculates the preFactor_ in barn for the cross section calculation which is given by
\[ c= \frac{(\hbar c)^2}{100} \cdot \frac{\pi}{2} \cdot \frac{A+1}{A \cdot u} \cdot \frac{1}{2\cdot(2J+1)} \]
Here is \(A \) and \(J\) the mass number and spin of the target nucleus, respectively. The factor 100 is for the conversion of fm to barn.
Returns
true or false, depending if the given reaction qvalue is valid.
References A_, compoundA_, compoundZ_, groundStateJ_, hbarc, isValid_, pi, preFactor_, pType_, NuclearMass::QValue(), qValue_, uconv, verbose_, and Z_.
Referenced by CrossSection().
PrintCrossSections()
void CrossSection::PrintCrossSections ()
References A_, crossSections_, NuclearMass::FindElement(), pType_, skipped_, and Z_.
Referenced by Module_OldSapphire::oldSapphire(), Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
PrintReactionRates()
void CrossSection::PrintReactionRates (bool macs)
References A_, NuclearMass::FindElement(), partFunc_, partFuncMACS_, pType_, reactionRates_, and Z_.
Referenced by Module_OldSapphire::oldSapphire().
PrintTransmissionTerms()
void CrossSection::PrintTransmissionTerms ()
References aExitTrans_, allowedJPi_, compoundA_, compoundZ_, crossSections_, entranceTrans_, NuclearMass::FindElement(), gExitTrans_, nExitTrans_, pExitTrans_, and skipped_.
Referenced by Module_OldSapphire::oldSapphire().
SetCalculateGammaCutoff()
static void CrossSection::SetCalculateGammaCutoff (bool calc) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetResidualAlpha()
static void CrossSection::SetResidualAlpha (bool residual) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetResidualGamma()
static void CrossSection::SetResidualGamma (bool residual) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetResidualNeutron()
static void CrossSection::SetResidualNeutron (bool residual) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetResidualProton()
static void CrossSection::SetResidualProton (bool residual) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
Member Data Documentation
A_
int CrossSection::A_ private
The mass number of the target nucleus
Referenced by CalcAllowedJPi(), CalcDecayerVector(), CalcPartitionFunc(), FindInitialState(), InitializeSeperationEnergies(), PreSetCompound(), PrintCrossSections(), and PrintReactionRates().
aExitTrans_
std::map<int, std::vector<double> > CrossSection::aExitTrans_ private
Referenced by CalcAllowedJPi(), Calculate(), and PrintTransmissionTerms().
allowedJPi_
std::vector<std::pair<double,int> > CrossSection::allowedJPi_ private
Referenced by CalcAllowedJPi(), CalcDecayerVector(), and PrintTransmissionTerms().
calcRates_
bool CrossSection::calcRates_ private
Referenced by CrossSection().
calculateGammaCutoff_
bool CrossSection::calculateGammaCutoff_ static private
Referenced by Calculate().
compoundA_
int CrossSection::compoundA_ private
The mass number of the compound nucleus
Referenced by CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), CalcDecayerVector(), Calculate(), CalculateEnergyGrid(), CalculateReactionRates(), CheckChannels(), PreSetCompound(), and PrintTransmissionTerms().
compoundZ_
int CrossSection::compoundZ_ private
The charge number of the compound nucleus
Referenced by CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), CalcDecayerVector(), Calculate(), CalculateEnergyGrid(), CheckChannels(), PreSetCompound(), and PrintTransmissionTerms().
crossSections_
std::vector<std::pair<double,CrossSectionValues> > CrossSection::crossSections_ private
Referenced by Calculate(), CalculateEnergyGrid(), CalculateReactionRates(), CrossSection(), FillEnergies(), PrintCrossSections(), and PrintTransmissionTerms().
dE_
constexpr double CrossSection::dE_ = .1 static private
Referenced by CrossSection().
energiesGiven_
bool CrossSection::energiesGiven_ private
Referenced by Calculate(), CrossSection(), and FillEnergies().
entranceState_
int CrossSection::entranceState_ private
The number of the entranceState in the level scheme
Referenced by Calculate(), FindInitialState(), and InitializeSeperationEnergies().
entranceTrans_
std::map<int, std::vector<double> > CrossSection::entranceTrans_ private
Referenced by CalcAllowedJPi(), Calculate(), and PrintTransmissionTerms().
exitStates_
std::vector<int> CrossSection::exitStates_ private
Referenced by Calculate(), and CheckChannels().
gammaCutoffSet_
bool CrossSection::gammaCutoffSet_ private
Referenced by Calculate().
gExitTrans_
std::map<int, std::vector<double> > CrossSection::gExitTrans_ private
Referenced by CalcAllowedJPi(), Calculate(), and PrintTransmissionTerms().
groundStateJ_
double CrossSection::groundStateJ_ private
Referenced by CalcAllowedJPi(), CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), CalcDecayerVector(), CalcPartitionFunc(), FindInitialState(), and PreSetCompound().
groundStatePi_
int CrossSection::groundStatePi_ private
The parit of the groundState
Referenced by CalcAllowedJPi(), CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), CalcDecayerVector(), and FindInitialState().
isValid_
bool CrossSection::isValid_ private
Referenced by CalculateEnergyGrid(), CrossSection(), FindInitialState(), and PreSetCompound().
macsEnergies_
std::vector< double > CrossSection::macsEnergies_ static private
Referenced by CalcPartitionFunc(), CalculateReactionRates(), and CreateMACSEnergiesVector().
maxEnergy_
constexpr double CrossSection::maxEnergy_ = 15.0 static private
Referenced by CrossSection().
minEnergy_
constexpr double CrossSection::minEnergy_ = 0.001 static private
Referenced by CrossSection().
nExitTrans_
std::map<int, std::vector<double> > CrossSection::nExitTrans_ private
Referenced by CalcAllowedJPi(), Calculate(), and PrintTransmissionTerms().
partFunc_
std::vector<std::pair<double,double> > CrossSection::partFunc_ private
Referenced by CalcPartitionFunc(), and PrintReactionRates().
partFuncMACS_
std::vector<std::pair<double,double> > CrossSection::partFuncMACS_ private
Referenced by CalcPartitionFunc(), and PrintReactionRates().
pExitTrans_
std::map<int, std::vector<double> > CrossSection::pExitTrans_ private
Referenced by CalcAllowedJPi(), Calculate(), and PrintTransmissionTerms().
preFactor_
double CrossSection::preFactor_ private
Referenced by Calculate(), and PreSetCompound().
pType_
int CrossSection::pType_ private
Integer which defines the type of the projectile
Referenced by CalcAllowedJPi(), Calculate(), CalculateEnergyGrid(), CalculateReactionRates(), CrossSection(), PreSetCompound(), PrintCrossSections(), and PrintReactionRates().
qValue_
double CrossSection::qValue_ private
Referenced by InitializeSeperationEnergies(), and PreSetCompound().
rateTemps_
std::vector< double > CrossSection::rateTemps_ static private
Referenced by CalcPartitionFunc(), CalculateEnergyGrid(), CalculateReactionRates(), and CreateTempVector().
reactionRates_
std::vector<std::pair<double,CrossSectionValues> > CrossSection::reactionRates_ private
Referenced by CalculateReactionRates(), and PrintReactionRates().
residualAlpha_
bool CrossSection::residualAlpha_ static private
Bool if residualAlpha should be toggled
Referenced by Calculate().
residualGamma_
bool CrossSection::residualGamma_ static private
Bool if residualGamma should be toggled
Referenced by Calculate().
residualNeutron_
bool CrossSection::residualNeutron_ static private
Bool if residualNeutron should be toggled
Referenced by Calculate().
residualProton_
bool CrossSection::residualProton_ static private
Bool if residualProton should be toggled
Referenced by Calculate().
seperationEnergy_
double CrossSection::seperationEnergy_ private
Referenced by CalcAverageDWaveResWidth(), CalcAveragePWaveResWidth(), CalcAverageSWaveResWidth(), Calculate(), CalculateEnergyGrid(), CrossSection(), and InitializeSeperationEnergies().
skipEnergy_
double CrossSection::skipEnergy_ private
Referenced by Calculate(), and CalculateEnergyGrid().
skipped_
std::vector<bool> CrossSection::skipped_ private
Referenced by Calculate(), CalculateReactionRates(), PrintCrossSections(), and PrintTransmissionTerms().
specifiedExitJ_
std::vector<double> CrossSection::specifiedExitJ_ private
Referenced by Calculate(), CheckChannels(), and InitializeSeperationEnergies().
specifiedExitPi_
std::vector<int> CrossSection::specifiedExitPi_ private
Referenced by Calculate(), CheckChannels(), and InitializeSeperationEnergies().
specifiedExitSepE_
std::vector<double> CrossSection::specifiedExitSepE_ private
Referenced by Calculate(), CheckChannels(), and InitializeSeperationEnergies().
verbose_
bool CrossSection::verbose_ =true private
Referenced by CalcAllowedJPi(), Calculate(), CalculateEnergyGrid(), CheckChannels(), FillEnergies(), InitializeSeperationEnergies(), and PreSetCompound().
Z_
int CrossSection::Z_ private
The atomic number of the target nucleus
Referenced by CalcDecayerVector(), CalcPartitionFunc(), FindInitialState(), InitializeSeperationEnergies(), PreSetCompound(), PrintCrossSections(), PrintReactionRates(), and Module_CrossSection::Run().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/CrossSection.h
/home/pscholz/SAPPHIRE/src/CrossSection.cpp
/home/pscholz/SAPPHIRE/src/Setup.cpp