Sapphire: Decayer Class Reference
Decayer Class Reference
#include <Decayer.h>
Public Member Functions
Decayer (int Z, int A, double jInitial, int piInitial, double energy, double totalWidthForCorrection=0., double uncorrTotalWidthForCorrection=0., double uncorrTotalWidthSqrdForCorrection=0., Decayer *widthCorrectedDecayer=NULL)
~Decayer ()
bool Decay (int &, int &, double &, int &, double &, double &)
void PrintFunctions ()
void PrintCDF ()
void CorrectWidthFluctuations ()
double NeutronEntranceWidth () const
double ProtonEntranceWidth () const
double AlphaEntranceWidth () const
double GammaEntranceWidth () const
double GammaTotalWidth () const
double NeutronTotalWidth () const
double AlphaTotalWidth () const
double ProtonTotalWidth () const
Static Public Member Functions
static void SetCrossSection (bool isCrossSection)
static void SetMaxL (double maxL)
static double GetMaxL ()
Friends
class CrossSection
Constructor & Destructor Documentation
Decayer::Decayer (int Z, int A, double jInitial, int piInitial, double energy, double totalWidthForCorrection = 0., double uncorrTotalWidthForCorrection = 0., double uncorrTotalWidthSqrdForCorrection = 0., Decayer * widthCorrectedDecayer = NULL)
References NuclearLevels::FindLevels(), TransitionRateFunc::GroundStateTransmission(), TransitionRateFunc::Integral(), and NuclearMass::QValue().
Referenced by CorrectWidthFluctuations().
Decayer::~Decayer ()
Member Function Documentation
double Decayer::AlphaEntranceWidth () const inline
Referenced by DecayController::Decay().
double Decayer::AlphaTotalWidth () const inline
Referenced by DecayController::Decay().
void Decayer::CorrectWidthFluctuations ()
References Decayer().
bool Decayer::Decay (int & Z, int & A, double & jFinal, int & piFinal, double & excitationEnergy, double & decayEnergy)
References randomSeed.
Referenced by DecayController::Decay().
double Decayer::GammaEntranceWidth () const inline
Referenced by DecayController::Decay().
double Decayer::GammaTotalWidth () const inline
Referenced by DecayController::Decay().
static double Decayer::GetMaxL () inline static
Referenced by parseCommandLineForOptions().
double Decayer::NeutronEntranceWidth () const inline
Referenced by DecayController::Decay().
double Decayer::NeutronTotalWidth () const inline
Referenced by DecayController::Decay().
void Decayer::PrintCDF ()
void Decayer::PrintFunctions ()
double Decayer::ProtonEntranceWidth () const inline
Referenced by DecayController::Decay().
double Decayer::ProtonTotalWidth () const inline
Referenced by DecayController::Decay().
static void Decayer::SetCrossSection (bool isCrossSection) inline static
Referenced by Initialize(), and main().
static void Decayer::SetMaxL (double maxL) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
Friends And Related Function Documentation
friend class CrossSection friend
The documentation for this class was generated from the following files:
include/Decayer.h
src/Decayer.cpp
src/Setup.cpp