Sapphire: NuclearMass Class Reference
NuclearMass Class Reference
#include <NuclearMass.h>
Static Public Member Functions
static void InitializeElements ()
static void InitializeMasses (std::string)
static int FindZ (std::string)
static std::string FindElement (int)
static bool FindMass (int, int, double &)
static bool MassDifference (int, int, int, int, double &)
Calculate the mass difference between two isotopes and writes it in "difference". Returns False if the mass cannot be found.
static double MassDifference (int, int, int, int)
Calculate the mass difference between two isotopes and returns it as double. If the mass cannot be found, an exception is thrown.
static bool QValue (int, int, int, int, double &)
static bool NeutronPairingGap (int, int, double &)
static bool ProtonPairingGap (int, int, double &)
static bool MicroEnergyCorr (int, int, double &)
static bool HighestBoundEnergy (int, int, double &)
static double CalculateLDMMass (int, int)
Static Private Attributes
static MassTable massTable_
static ElementTable elementTable_
Member Function Documentation
CalculateLDMMass()
double NuclearMass::CalculateLDMMass (int Z, int A) static
Calculates liquid drop model mass based on TALYS parametrization.
References uconv.
FindElement()
std::string NuclearMass::FindElement (int Z) static
References elementTable_.
Referenced by DecayResults::DecayResults(), CrossSection::PrintCrossSections(), CrossSection::PrintReactionRates(), and CrossSection::PrintTransmissionTerms().
FindMass()
bool NuclearMass::FindMass (int Z, int A, double & M) static
References HAS_EXP_MASS, HAS_TH_MASS, and massTable_.
Referenced by DecayController::CalcKinematics(), GammaTransmissionFunc::GammaTransmissionFunc(), MassDifference(), ParticleTransmissionFunc::ParticleTransmissionFunc(), and QValue().
FindZ()
int NuclearMass::FindZ (std::string element) static
References elementTable_.
Referenced by SapphireInput::atomicNumberIntFromIsotopeString(), SapphireInput::atomicNumberIntFromReactionString(), Module_Decayer::atomicNumberIntFromString(), Module_CrossSection::atomicNumberIntFromString(), Module_OldSapphire::parseCommandLineForDecay(), and Module_OldSapphire::parseCommandLineForXS().
HighestBoundEnergy()
bool NuclearMass::HighestBoundEnergy (int Z, int A, double & energy) static
References QValue().
Referenced by TransitionRateFunc::TransitionRateFunc().
InitializeElements()
void NuclearMass::InitializeElements () static
Referenced by Initialize().
InitializeMasses()
void NuclearMass::InitializeMasses (std::string filename) static
References HAS_EXP_MASS, HAS_TH_MASS, massTable_, and uconv.
Referenced by Initialize().
MassDifference() [1/2]
bool NuclearMass::MassDifference (int Z1, int A1, int Z2, int A2, double & difference) static
Calculate the mass difference between two isotopes and writes it in "difference". Returns False if the mass cannot be found.
Parameters
Z1 Charge of Isotope 1
A1 Massnumber of Isotope 1
Z2 Charge of Isotope 2
A2 Massnumber of Isotope 2
difference reference to the mass difference double
Returns
Returns a True or False depending on if the masses of both isotopes have been found by FindMass()
References FindMass().
Referenced by NeutronPairingGap(), ProtonPairingGap(), and QValue().
MassDifference() [2/2]
double NuclearMass::MassDifference (int Z1, int A1, int Z2, int A2) static
Calculate the mass difference between two isotopes and returns it as double. If the mass cannot be found, an exception is thrown.
Parameters
Z1 Charge of Isotope 1
A1 Massnumber of Isotope 1
Z2 Charge of Isotope 2
A2 Massnumber of Isotope 2
Returns
Returns a True or False depending on if the masses of both isotopes have been found by FindMass()
References FindMass().
MicroEnergyCorr()
bool NuclearMass::MicroEnergyCorr (int Z, int A, double & correction) static
References massTable_.
Referenced by RauscherLevelDensity::RauscherLevelDensity().
NeutronPairingGap()
bool NuclearMass::NeutronPairingGap (int Z, int A, double & pairingGap) static
References MassDifference().
Referenced by RauscherLevelDensity::CalcBackShift().
ProtonPairingGap()
bool NuclearMass::ProtonPairingGap (int Z, int A, double & pairingGap) static
References MassDifference().
Referenced by RauscherLevelDensity::CalcBackShift().
QValue()
bool NuclearMass::QValue (int Z1, int A1, int Z2, int A2, double & qValue) static
References FindMass(), and MassDifference().
Referenced by CrossSection::CalculateEnergyGrid(), CrossSection::CheckChannels(), Decayer::Decayer(), HighestBoundEnergy(), KopeckyUhlGSF::KopeckyUhlGSF(), ParticleHoleLevelDensity::ParticleHoleLevelDensity(), PreEqDecayer::PreEqDecayer(), and CrossSection::PreSetCompound().
Member Data Documentation
elementTable_
ElementTable NuclearMass::elementTable_ static private
Referenced by FindElement(), and FindZ().
massTable_
MassTable NuclearMass::massTable_ static private
Referenced by FindMass(), InitializeMasses(), and MicroEnergyCorr().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/NuclearMass.h
/home/pscholz/SAPPHIRE/src/NuclearMass.cpp
/home/pscholz/SAPPHIRE/src/Setup.cpp