language: cpp
os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - doxygen
      - libgsl-dev
      - libboost-all-dev
      - libomp-dev
      - libxpm-dev


install:
  - cd ${TRAVIS_BUILD_DIR}/..
  - git clone https://github.com/root-project/root.git root
  - mkdir build
  - cd build
  - cmake ../root
  - make -j8
  - source bin/thisroot.sh
  - cd ${TRAVIS_BUILD_DIR}
  - bash build.sh