language: cpp
os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - doxygen
      - libgsl-dev
      - libboost-all-dev
      - libomp-dev
      - libxpm-dev

install:
  - cd ${TRAVIS_BUILD_DIR}/..
  - wget https://root.cern/download/root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - tar -xzvf root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - source root/bin/thisroot.sh
  - cd ${TRAVIS_BUILD_DIR}
  - bash build.sh