language: cpp
os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - doxygen
      - cppcheck
      - libgsl-dev
      - libboost-all-dev
      - libomp-dev
      - libxpm-dev
      - lcov

before_install:
  # Getting root binaries
  - cd ${TRAVIS_BUILD_DIR}/..
  - wget --quiet https://root.cern/download/root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - tar -xzf root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - source root/bin/thisroot.sh
  
install:  
  # build the project
  - cd ${TRAVIS_BUILD_DIR}
  - bash build.sh

script:
  # run the project
  - build/sapphire reaction examples/test_89Y+p.ini

 after_success:
  # lcov
  - lcov --directory . --capture --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) - f coverage.info || echo "No lcov report"
  # cpp check src
  - cppcheck --xml src/ > report_src.xml
  # code covarage
  - bash <(curl -s https://codecov.io/bash) -f report_src.xml || echo "No cppcheck report"