language: cpp
os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - doxygen
      - cppcheck
      - libgsl-dev
      - libboost-all-dev
      - libomp-dev
      - libxpm-dev

before install:
  # Getting root binaries
  - cd ${TRAVIS_BUILD_DIR}/..
  - wget https://root.cern/download/root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - tar -xzvf root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - source root/bin/thisroot.sh
  
install:  
  # build the project
  - cd ${TRAVIS_BUILD_DIR}
  - bash build.sh

script:
 # run the project
 - build/sapphire reaction examples/test_89Y+p.ini
 # cpp check src
 - cppcheck --xml src/
 # cpp check include
 - cppcheck --xml include/
 # code covarage
 - bash <(curl -s https://codecov.io/bash)