Sapphire: TransitionRateFunc Class Reference
TransitionRateFunc Class Reference
#include <TransitionRateFunc.h>
Public Member Functions
TransitionRateFunc (int, int, int, int, double, int, double, int, double, int, double, double, double, double, double, double, TransitionRateFunc *, bool)
~TransitionRateFunc ()
std::vector< XYPair > const Function ()
std::vector< XYPair > const CumulativeSum ()
double Integral () const
double CalcLevelDensity (double energy)
double CalcTransmissionFunc (double energy)
double CalcTotalLevelDensity (double energy)
double ExclusiveBranching () const
double GroundStateTransmission () const
Static Public Member Functions
static void SetGammaCutoffEnergy (double energy)
static double GetGammaCutoffEnergy ()
Private Attributes
double integral_
double exclusiveBranching_
double groundStateTransmission_
std::vector< XYPair > function_
std::vector< XYPair > cumulativeSum_
LevelDensity * levelDensity_
TransmissionFunc * transmissionFunc_
Static Private Attributes
static const int numCrossSectionSteps_ =20
static double gammaCutoffEnergy_
Constructor & Destructor Documentation
TransitionRateFunc()
TransitionRateFunc::TransitionRateFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double compoundE, double qValue, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransitionRateFunc * previous, bool isCrossSection)
References CalcLevelDensity(), CalcTransmissionFunc(), GammaTransmissionFunc::CreateGammaTransmissionFunc(), ParticleTransmissionFunc::CreateParticleTransmissionFunc(), cumulativeSum_, exclusiveBranching_, NuclearLevels::FindLevels(), function_, gammaCutoffEnergy_, groundStateTransmission_, NuclearMass::HighestBoundEnergy(), integral_, TransmissionFunc::IsValid(), levelDensity_, and transmissionFunc_.
~TransitionRateFunc()
TransitionRateFunc::~TransitionRateFunc () inline
Member Function Documentation
CalcLevelDensity()
double TransitionRateFunc::CalcLevelDensity (double energy) inline
Referenced by TransitionRateFunc().
CalcTotalLevelDensity()
double TransitionRateFunc::CalcTotalLevelDensity (double energy) inline
CalcTransmissionFunc()
double TransitionRateFunc::CalcTransmissionFunc (double energy) inline
Referenced by TransitionRateFunc().
CumulativeSum()
std::vector<XYPair> const TransitionRateFunc::CumulativeSum () inline
ExclusiveBranching()
double TransitionRateFunc::ExclusiveBranching () const inline
Function()
std::vector<XYPair> const TransitionRateFunc::Function () inline
GetGammaCutoffEnergy()
static double TransitionRateFunc::GetGammaCutoffEnergy () inline static
Referenced by Module_OldSapphire::parseCommandLineForOptions().
GroundStateTransmission()
double TransitionRateFunc::GroundStateTransmission () const inline
Referenced by Decayer::Decayer().
Integral()
double TransitionRateFunc::Integral () const inline
Referenced by Decayer::Decayer().
SetGammaCutoffEnergy()
static void TransitionRateFunc::SetGammaCutoffEnergy (double energy) inline static
Referenced by CrossSection::Calculate(), Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
Member Data Documentation
cumulativeSum_
std::vector<XYPair> TransitionRateFunc::cumulativeSum_ private
Referenced by TransitionRateFunc().
exclusiveBranching_
double TransitionRateFunc::exclusiveBranching_ private
Referenced by TransitionRateFunc().
function_
std::vector<XYPair> TransitionRateFunc::function_ private
Referenced by TransitionRateFunc().
gammaCutoffEnergy_
double TransitionRateFunc::gammaCutoffEnergy_ static private
Referenced by TransitionRateFunc().
groundStateTransmission_
double TransitionRateFunc::groundStateTransmission_ private
Referenced by TransitionRateFunc().
integral_
double TransitionRateFunc::integral_ private
Referenced by TransitionRateFunc().
levelDensity_
LevelDensity* TransitionRateFunc::levelDensity_ private
Referenced by TransitionRateFunc().
numCrossSectionSteps_
const int TransitionRateFunc::numCrossSectionSteps_ =20 static private
transmissionFunc_
TransmissionFunc* TransitionRateFunc::transmissionFunc_ private
Referenced by TransitionRateFunc().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/TransitionRateFunc.h
/home/pscholz/SAPPHIRE/src/Setup.cpp
/home/pscholz/SAPPHIRE/src/TransitionRateFunc.cpp