Sapphire: GammaTransmissionFunc Class Reference
GammaTransmissionFunc Class Reference abstract
#include <GammaTransmissionFunc.h>
Public Member Functions
GammaTransmissionFunc (int, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
virtual ~GammaTransmissionFunc ()
bool IsValid ()
double operator() (double)
virtual double CalcStrengthFunction (double)=0
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Static Public Member Functions
static GammaTransmissionFunc * CreateGammaTransmissionFunc (int, int, double, int, double, int, double, LevelDensity *, double, double, double, TransmissionFunc *, double)
static void InitializeGDRParameters (std::string)
static void SetEGDRType (int)
static void SetPorterThomas (bool)
Protected Attributes
GDRParameters gdrParameters_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Static Protected Attributes
static GDRTable gdrTable_
static int egdrType_
static const int mgdrType_ =0
static const int egqrType_ =0
static bool porterThomas_
Constructor & Destructor Documentation
GammaTransmissionFunc()
GammaTransmissionFunc::GammaTransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous)
References NuclearMass::FindMass(), fstruc, gdrParameters_, gdrTable_, hbarc, GDRParameters::kSigmaGamma_, TransmissionFunc::m2_, pi, and TransmissionFunc::z2_.
~GammaTransmissionFunc()
virtual GammaTransmissionFunc::~GammaTransmissionFunc () inline virtual
Member Function Documentation
CalcStrengthFunction()
virtual double GammaTransmissionFunc::CalcStrengthFunction (double) pure virtual
Implemented in BrinkAxelGSF, KopeckyUhlGSF, and McCullaghGSF.
Referenced by operator()().
CreateGammaTransmissionFunc()
GammaTransmissionFunc * GammaTransmissionFunc::CreateGammaTransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, LevelDensity * levelDensity, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous, double compoundE) static
References egdrType_, egqrType_, and mgdrType_.
Referenced by TransitionRateFunc::TransitionRateFunc().
InitializeGDRParameters()
void GammaTransmissionFunc::InitializeGDRParameters (std::string filename) static
References gdrTable_.
Referenced by Initialize().
IsValid()
bool GammaTransmissionFunc::IsValid () inline virtual
Implements TransmissionFunc.
operator()()
double GammaTransmissionFunc::operator() (double energy) virtual
Implements TransmissionFunc.
References CalcStrengthFunction(), TransmissionFunc::maxL_, pi, porterThomas_, TransmissionFunc::previous_, randomSeed, TransmissionFunc::totalWidthForCorrection_, TransmissionFunc::uncorrTotalWidthForCorrection_, and TransmissionFunc::uncorrTotalWidthSqrdForCorrection_.
SetEGDRType()
void GammaTransmissionFunc::SetEGDRType (int type) static
References egdrType_.
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetPorterThomas()
void GammaTransmissionFunc::SetPorterThomas (bool yn) static
References porterThomas_.
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
Member Data Documentation
egdrType_
int GammaTransmissionFunc::egdrType_ static protected
Referenced by CreateGammaTransmissionFunc(), and SetEGDRType().
egqrType_
const int GammaTransmissionFunc::egqrType_ =0 static protected
Referenced by CreateGammaTransmissionFunc().
gdrParameters_
GDRParameters GammaTransmissionFunc::gdrParameters_ protected
Referenced by McCullaghGSF::CalcEnergyDependentWidth(), KopeckyUhlGSF::CalcEnergyDependentWidth(), BrinkAxelGSF::CalcEnergyDependentWidth(), McCullaghGSF::CalcStrengthFunction(), KopeckyUhlGSF::CalcStrengthFunction(), BrinkAxelGSF::CalcStrengthFunction(), and GammaTransmissionFunc().
gdrTable_
GDRTable GammaTransmissionFunc::gdrTable_ static protected
Referenced by GammaTransmissionFunc(), and InitializeGDRParameters().
mgdrType_
const int GammaTransmissionFunc::mgdrType_ =0 static protected
Referenced by CreateGammaTransmissionFunc().
porterThomas_
bool GammaTransmissionFunc::porterThomas_ static protected
Referenced by operator()(), and SetPorterThomas().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/GammaTransmissionFunc.h
/home/pscholz/SAPPHIRE/src/GammaTransmissionFunc.cpp
/home/pscholz/SAPPHIRE/src/Setup.cpp