Sapphire: Module_OldSapphire Namespace Reference
Module_OldSapphire Namespace Reference
Classes
struct EntrancePairs
Typedefs
typedef struct Module_OldSapphire::EntrancePairs EntrancePairs
Functions
void Go (int argc, char *argv[])
int oldSapphire_MPI (int argc, char *argv[])
int oldSapphire (int argc, char *argv[])
void parseCommandLineForOptions (std::vector< std::string > &args, int &suffixNo, bool &preEq, int &numPiParticles, int &numPiHoles, int &numNuParticles, int &numNuHoles)
bool parseCommandLineForXS (std::vector< std::string > &args, int &Z, int &A, int &pType, std::string &energyFile, bool asciiIn)
CMD line parameters are parsed for the Cross section module.
bool parseCommandLineForDecay (std::vector< std::string > &args, int &Z, int &A, double &J, int &Pi, double &lowEnergy, double &highEnergy, int &events)
CMD line parameters are parsed for the Decay module.
void printHelp ()
void parseCommandLineForOptions (std::vector< std::string > &args, int &suffixNo, bool &preEq, int &numPiParticles, int &numPiHoles, int &numNuParticles, int &numNuHoles, bool &calcAverageWidth, bool &calcRates, bool &asciiIn, std::string &inFile, int &entranceState, std::vector< int > &exitStates, bool &printTrans)
Detailed Description
Currently only used for the Decayer
Typedef Documentation
EntrancePairs
typedef struct Module_OldSapphire::EntrancePairs Module_OldSapphire::EntrancePairs
Function Documentation
Go()
void Module_OldSapphire::Go (int argc, char * argv[])
Top level function to call from main
References oldSapphire().
Referenced by main().
oldSapphire()
int Module_OldSapphire::oldSapphire (int argc, char * argv[])
Top level function to call from main
Calling the Initialize() function from Setup.cpp
Create a vector which containts the cmd parameter. Now int i starts at 1, the first parameter is "old" now.
Define sum variables which will be needed for the cmd line parsing
Parse optional cmd line arguments
Random number generator seeding?
Fill the randomSeed array with 12 random numbers
Apparently here is an undocumented option to make calculations for more than one reaction. This is probably enabled by the "--in=" keyword. See parseCommandLineForOptions().
Apparently, a file was given with for than one reaction. So, now it will be checked if the file can be read. If not, the program exits. If, then EntrancePairs will be generated and pushed back in entrancePairs.
The Decayer is informed, that a CrossSection calculation will happen.
If no ascii-file was given, then the length of the following loop is 1.
If an ascii-file was given
If there are more arguments, then we are apparently in the statistical decay calculations, right? This needs to change. This can be made much more readable and maintainable.
< Portion of events which are written to the root tree.
Apparently placeholders for cmd line parameters
Apparently placeholders for cmd line parameters
Cmd line parameters for the decay mode will be read.
Ah, I see. The total events will be divided in chunks.
Initialize the counting of decays.
Using Open Multiprocessing (OMP) for the parallel execution of the following for-loop. Nice.
Calling the Initialize() function from Setup.cpp
Create a vector which containts the cmd parameter. Now int i starts at 1, the first parameter is "old" now.
Define sum variables which will be needed for the cmd line parsing
Parse optional cmd line arguments
Random number generator seeding?
Fill the randomSeed array with 12 random numbers
Apparently here is an undocumented option to make calculations for more than one reaction. This is probably enabled by the "--in=" keyword. See parseCommandLineForOptions().
Apparently, a file was given with for than one reaction. So, now it will be checked if the file can be read. If not, the program exits. If, then EntrancePairs will be generated and pushed back in entrancePairs.
The Decayer is informed, that a CrossSection calculation will happen.
If no ascii-file was given, then the length of the following loop is 1.
If an ascii-file was given
If there are more arguments, then we are apparently in the statistical decay calculations, right? This needs to change. This can be made much more readable and maintainable.
< Portion of events which are written to the root tree.
Apparently placeholders for cmd line parameters
Apparently placeholders for cmd line parameters
Cmd line parameters for the decay mode will be read.
Ah, I see. The total events will be divided in chunks.
Initialize the counting of decays.
Using Open Multiprocessing (OMP) for the parallel execution of the following for-loop. Nice.
References Module_OldSapphire::EntrancePairs::A_, DecayResults::AddResults(), CrossSection::CalcAverageDWaveResWidth(), CrossSection::CalcAveragePWaveResWidth(), CrossSection::CalcAverageSWaveResWidth(), CrossSection::Calculate(), CrossSection::CalculateReactionRates(), DecayController::Decay(), DecayController::DecayProducts(), Module_OldSapphire::EntrancePairs::EntrancePairs(), CrossSection::IsValid(), parseCommandLineForDecay(), parseCommandLineForOptions(), parseCommandLineForXS(), CrossSection::PrintCrossSections(), DecayController::PrintDecays(), printHelp(), CrossSection::PrintReactionRates(), CrossSection::PrintTransmissionTerms(), Module_OldSapphire::EntrancePairs::pType_, randomSeed, Decayer::SetCrossSection(), ProgressBar::start(), ProgressBar::update(), and Module_OldSapphire::EntrancePairs::Z_.
Referenced by Go().
oldSapphire_MPI()
int Module_OldSapphire::oldSapphire_MPI (int argc, char * argv[])
Top level function to call from main
parseCommandLineForDecay()
bool Module_OldSapphire::parseCommandLineForDecay (std::vector< std::string > & args, int & Z, int & A, double & J, int & Pi, double & lowEnergy, double & highEnergy, int & events)
Parameters
args cmd line string
Z nuclear charge number
A nuclear mass number
J Reference to a spin double
Pi Reference to a parity int
lowEnergy Reference to a lowEnergy double
highEnergy Reference to a highEnergy double
events Reference to the events int.
Returns
True or False
Note
This has to move to another class in future. This does not belong in a main file but in the class file of the respective module.
References NuclearMass::FindZ().
Referenced by oldSapphire().
parseCommandLineForOptions() [1/2]
void Module_OldSapphire::parseCommandLineForOptions (std::vector< std::string > & args, int & suffixNo, bool & preEq, int & numPiParticles, int & numPiHoles, int & numNuParticles, int & numNuHoles)
Referenced by oldSapphire().
parseCommandLineForOptions() [2/2]
void Module_OldSapphire::parseCommandLineForOptions (std::vector< std::string > & args, int & suffixNo, bool & preEq, int & numPiParticles, int & numPiHoles, int & numNuParticles, int & numNuHoles, bool & calcAverageWidth, bool & calcRates, bool & asciiIn, std::string & inFile, int & entranceState, std::vector< int > & exitStates, bool & printTrans)
References TransitionRateFunc::GetGammaCutoffEnergy(), Decayer::GetMaxL(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), Decayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), and CrossSection::SetResidualProton().
parseCommandLineForXS()
bool Module_OldSapphire::parseCommandLineForXS (std::vector< std::string > & args, int & Z, int & A, int & pType, std::string & energyFile, bool asciiIn)
Parameters
args cmd line string
Z nuclear charge number
A nuclear mass number
pType Projectile
energyFile Reference to the string for the path to the EnergyFile
asciiIn Boolean which shows if there is a asciiFile or not
highEnergy Reference to a highEnergy double
events Reference to the events int.
Returns
True or False
Note
This has to move to another class in future. This does not belong in a main file but in the class file of the respective module.
References NuclearMass::FindZ().
Referenced by oldSapphire().
printHelp()
void Module_OldSapphire::printHelp ()
The old printHelp() function
Referenced by oldSapphire().