Sapphire: DecayController Class Reference
DecayController Class Reference
#include <DecayController.h>
Public Member Functions
DecayController (int Z, int A, double jInitial, int piInitial, double energy, int initialNeutronNumber=-1, int initialNeutronHoleNumber=-1, int initialProtonNumber=-1, int initialProtonHoleNumber=-1)
bool Decay (double &, double &, double &, double &, double &, double &, double &, double &)
std::vector< DecayProduct > DecayProducts () const
void PrintDecays ()
Private Member Functions
void CalcKinematics (int, int, int, int, double, double, int, double, TVector3 &)
Private Attributes
int Z_
int A_
int piInitial_
int initialNeutronNumber_
int initialNeutronHoleNumber_
int initialProtonNumber_
int initialProtonHoleNumber_
double jInitial_
double energy_
std::vector< DecayProduct > decayProducts_
Static Private Attributes
static constexpr double thresholdEnergy_ =0.05
Constructor & Destructor Documentation
DecayController()
DecayController::DecayController (int Z, int A, double jInitial, int piInitial, double energy, int initialNeutronNumber = -1, int initialNeutronHoleNumber = -1, int initialProtonNumber = -1, int initialProtonHoleNumber = -1) inline
References Decay().
Member Function Documentation
CalcKinematics()
void DecayController::CalcKinematics (int daughterZ, int daughterA, int parentZ, int parentA, double daughterEnergy, double daughterJ, int daughterPi, double decayEnergy, TVector3 & parentBeta) private
References decayProducts_, NuclearMass::FindMass(), pi, and randomSeed.
Referenced by Decay(), and DecayProducts().
Decay()
bool DecayController::Decay (double & neutronEntrance, double & protonEntrance, double & alphaEntrance, double & gammaEntrance, double & neutronTotalWidth, double & protonTotalWidth, double & alphaTotalWidth, double & gammaTotalWidth)
References A_, Decayer::AlphaEntranceWidth(), Decayer::AlphaTotalWidth(), CalcKinematics(), PreEqDecayer::Decay(), Decayer::Decay(), energy_, Decayer::GammaEntranceWidth(), Decayer::GammaTotalWidth(), initialNeutronHoleNumber_, initialNeutronNumber_, initialProtonHoleNumber_, initialProtonNumber_, jInitial_, Decayer::NeutronEntranceWidth(), Decayer::NeutronTotalWidth(), piInitial_, Decayer::ProtonEntranceWidth(), Decayer::ProtonTotalWidth(), thresholdEnergy_, and Z_.
Referenced by DecayController(), Module_OldSapphire::oldSapphire(), and Module_Decayer::Run().
DecayProducts()
std::vector<DecayProduct> DecayController::DecayProducts () const inline
References CalcKinematics(), decayProducts_, and PrintDecays().
Referenced by Module_OldSapphire::oldSapphire(), and Module_Decayer::Run().
PrintDecays()
void DecayController::PrintDecays ()
References decayProducts_.
Referenced by DecayProducts(), Module_OldSapphire::oldSapphire(), and Module_Decayer::Run().
Member Data Documentation
A_
int DecayController::A_ private
Referenced by Decay().
decayProducts_
std::vector<DecayProduct> DecayController::decayProducts_ private
Referenced by CalcKinematics(), DecayProducts(), and PrintDecays().
energy_
double DecayController::energy_ private
Referenced by Decay().
initialNeutronHoleNumber_
int DecayController::initialNeutronHoleNumber_ private
Referenced by Decay().
initialNeutronNumber_
int DecayController::initialNeutronNumber_ private
Referenced by Decay().
initialProtonHoleNumber_
int DecayController::initialProtonHoleNumber_ private
Referenced by Decay().
initialProtonNumber_
int DecayController::initialProtonNumber_ private
Referenced by Decay().
jInitial_
double DecayController::jInitial_ private
Referenced by Decay().
piInitial_
int DecayController::piInitial_ private
Referenced by Decay().
thresholdEnergy_
constexpr double DecayController::thresholdEnergy_ =0.05 static private
Referenced by Decay().
Z_
int DecayController::Z_ private
Referenced by Decay().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/DecayController.h
/home/pscholz/SAPPHIRE/src/DecayController.cpp