Sapphire: Coulomb_wave_functions Class Reference
Coulomb_wave_functions Class Reference
#include <cwfcomp.H>
Public Member Functions
Coulomb_wave_functions (const bool is_it_normalized_c, const std::complex< double > &l_c, const std::complex< double > &eta_c)
~Coulomb_wave_functions (void)
void F_dF_init (const std::complex< double > &z, const std::complex< double > &F, const std::complex< double > &dF)
void F_dF (const std::complex< double > &z, std::complex< double > &F, std::complex< double > &dF)
void G_dG (const std::complex< double > &z, std::complex< double > &G, std::complex< double > &dG)
void H_dH (const int omega, const std::complex< double > &z, std::complex< double > &H, std::complex< double > &dH)
void H_dH_scaled (const int omega, const std::complex< double > &z, std::complex< double > &H, std::complex< double > &dH)
Public Attributes
const std::complex< double > l
const std::complex< double > eta
const bool is_it_normalized
Constructor & Destructor Documentation
Coulomb_wave_functions::Coulomb_wave_functions (const bool is_it_normalized_c, const std::complex< double > & l_c, const std::complex< double > & eta_c) inline
References eta, and is_it_normalized.
Coulomb_wave_functions::~Coulomb_wave_functions (void) inline
Member Function Documentation
void Coulomb_wave_functions::F_dF (const std::complex< double > & z, std::complex< double > & F, std::complex< double > & dF)
References is_it_normalized, isfinite(), SIGN, and sqrt_precision.
Referenced by G_dG(), H_dH(), H_dH_scaled(), and CoulFunc::operator()().
void Coulomb_wave_functions::F_dF_init (const std::complex< double > & z, const std::complex< double > & F, const std::complex< double > & dF)
void Coulomb_wave_functions::G_dG (const std::complex< double > & z, std::complex< double > & G, std::complex< double > & dG)
References F_dF(), H_dH(), is_it_normalized, isfinite(), and sqrt_precision.
Referenced by CoulFunc::operator()().
void Coulomb_wave_functions::H_dH (const int omega, const std::complex< double > & z, std::complex< double > & H, std::complex< double > & dH)
References F_dF(), is_it_normalized, isfinite(), and sqrt_precision.
Referenced by G_dG().
void Coulomb_wave_functions::H_dH_scaled (const int omega, const std::complex< double > & z, std::complex< double > & H, std::complex< double > & dH)
References F_dF(), is_it_normalized, isfinite(), and sqrt_precision.
Member Data Documentation
const std::complex<double> Coulomb_wave_functions::eta
Referenced by Coulomb_wave_functions().
const bool Coulomb_wave_functions::is_it_normalized
Referenced by Coulomb_wave_functions(), F_dF(), G_dG(), H_dH(), and H_dH_scaled().
const std::complex<double> Coulomb_wave_functions::l
The documentation for this class was generated from the following files:
coul/include/cwfcomp.H
coul/src/cwfcomp.cpp