Sapphire: EquivSquareWell Class Reference
EquivSquareWell Class Reference
#include <EquivSquareWell.h>
Public Member Functions
EquivSquareWell (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
~EquivSquareWell ()
double CalcTransmission (double, int, double)
Public Member Functions inherited from ParticleTransmissionFunc
ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~ParticleTransmissionFunc ()
bool IsValid ()
double operator() (double)
double operator() (double, int)
void CalcSLDependentFunctions (double, std::map< SLPair, double > &)
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Private Member Functions
double GetF ()
double GetV1 ()
double GetV0 ()
double GetR1 ()
double GetR0 ()
Private Attributes
CoulFunc * coulFunc_
Additional Inherited Members
Static Public Member Functions inherited from ParticleTransmissionFunc
static ParticleTransmissionFunc * CreateParticleTransmissionFunc (int, int, int, int, double, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
static void SetAlphaFormalism (int formalism)
static void SetNeutronFormalism (int formalism)
static void SetProtonFormalism (int formalism)
static void SetPorterThomas (bool)
Protected Attributes inherited from ParticleTransmissionFunc
int z1_
int m1_
int pType_
int parity_
double redmass_
double spin_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Constructor & Destructor Documentation
EquivSquareWell()
EquivSquareWell::EquivSquareWell (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous) inline
References coulFunc_, ParticleTransmissionFunc::redmass_, ParticleTransmissionFunc::z1_, and TransmissionFunc::z2_.
~EquivSquareWell()
EquivSquareWell::~EquivSquareWell () inline
References CalcTransmission(), coulFunc_, GetF(), GetR0(), GetR1(), GetV0(), and GetV1().
Member Function Documentation
CalcTransmission()
double EquivSquareWell::CalcTransmission (double s, int l, double energy) virtual
Implements ParticleTransmissionFunc.
References coulFunc_, GetF(), GetR1(), GetV1(), hbarc, CoulFunc::Penetrability(), pi, ParticleTransmissionFunc::redmass_, and uconv.
Referenced by ~EquivSquareWell().
GetF()
double EquivSquareWell::GetF () private
References ParticleTransmissionFunc::pType_.
Referenced by CalcTransmission(), and ~EquivSquareWell().
GetR0()
double EquivSquareWell::GetR0 () private
References TransmissionFunc::m2_, and ParticleTransmissionFunc::pType_.
Referenced by GetR1(), GetV1(), and ~EquivSquareWell().
GetR1()
double EquivSquareWell::GetR1 () private
References GetR0(), and ParticleTransmissionFunc::pType_.
Referenced by CalcTransmission(), GetV1(), and ~EquivSquareWell().
GetV0()
double EquivSquareWell::GetV0 () private
References ParticleTransmissionFunc::pType_.
Referenced by GetV1(), and ~EquivSquareWell().
GetV1()
double EquivSquareWell::GetV1 () private
References GetR0(), GetR1(), and GetV0().
Referenced by CalcTransmission(), and ~EquivSquareWell().
Member Data Documentation
coulFunc_
CoulFunc* EquivSquareWell::coulFunc_ private
Referenced by CalcTransmission(), EquivSquareWell(), and ~EquivSquareWell().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/EquivSquareWell.h
/home/pscholz/SAPPHIRE/src/EquivSquareWell.cpp