Sapphire: Module_Decayer Namespace Reference
Module_Decayer Namespace Reference
Functions
void Go (int argc, char *argv[])
void Run (const SapphireInput &input)
bool fexists (const char *filename)
Check wheter a string represents an actual file.
std::string atomicNumberStringFromString (std::string isotopeString)
Get the atomic number as string from isotopeString.
int atomicNumberIntFromString (std::string isotopeString)
Get the atomic number as int from isotopeString.
std::string massNumberStringFromString (std::string isotopeString)
Get the massNumberString from the isotopeString.
int massNumberIntFromString (std::string isotopeString)
Get the massNumberInt from the isotopeString.
void printHelp ()
Function Documentation
atomicNumberIntFromString()
int Module_Decayer::atomicNumberIntFromString (std::string isotopeString)
Get the atomic number as int from isotopeString.
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the isotopeString, e.g. 28 other wise returns 0.
References atomicNumberStringFromString(), and NuclearMass::FindZ().
Referenced by Run().
atomicNumberStringFromString()
std::string Module_Decayer::atomicNumberStringFromString (std::string isotopeString)
Get the atomic number as string from isotopeString.
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the isotopeString, e.g. Fe
References massNumberStringFromString().
Referenced by atomicNumberIntFromString().
fexists()
bool Module_Decayer::fexists (const char * filename)
Check wheter a string represents an actual file.
Parameters
filename String whith the supposedly path to a file.
Returns
True if the file exists; False if it doesn't.
Referenced by Go().
Go()
void Module_Decayer::Go (int argc, char * argv[])
Top level function to call from main
A clock is started at the beginning of Go() to measure the total calculation time.
If too few arguments are given for the decayer, being "program module inputFile", then the printHelp() method is called and the program exits.
In a next step it'll checked if the filename points to an actual file. If yes, the calculation can start. If not, the program exits.
If the inputFile exists:
an SapphireInput object is created
the content of the inputFile is printed to std::cout via printInputFile()
the inputFile is read by ReadInputFile()
the parameters in the Sapphire Input Object are printed via printInputParameters()
the Run() method is called, passing the SapphireInput object by reference
At the end of the Go() method the clock is stopped and the total calculation time is printed.
A clock is started at the beginning of Go() to measure the total calculation time.
If too few arguments are given for the decayer, being "program module inputFile", then the printHelp() method is called and the program exits.
In a next step it'll checked if the filename points to an actual file. If yes, the calculation can start. If not, the program exits.
If the inputFile exists:
an SapphireInput object is created
the content of the inputFile is printed to std::cout via printInputFile()
the inputFile is read by ReadInputFile()
the parameters in the Sapphire Input Object are printed via printInputParameters()
the Run() method is called, passing the SapphireInput object by reference
At the end of the Go() method the clock is stopped and the total calculation time is printed.
References fexists(), printHelp(), SapphireInput::printIntputFile(), SapphireInput::printIntputParameters(), SapphireInput::ReadInputFile(), and Run().
Referenced by main().
massNumberIntFromString()
int Module_Decayer::massNumberIntFromString (std::string isotopeString)
Get the massNumberInt from the isotopeString.
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the isotopeString, e.g. 60, if successful. Otherwise returns 0.
References massNumberStringFromString().
Referenced by Run().
massNumberStringFromString()
std::string Module_Decayer::massNumberStringFromString (std::string isotopeString)
Get the massNumberString from the isotopeString.
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the isotopeString, e.g. "60"
Referenced by atomicNumberStringFromString(), and massNumberIntFromString().
printHelp()
void Module_Decayer::printHelp ()
Referenced by Go().
Run()
void Module_Decayer::Run (const SapphireInput & input)
Declaration of the main function of the Decayer Module
At first the parameters needed to be initialized for the old Sapphire code are obtained from the SapphireInput object passed by reference to the Module_Decayer::Run() method.
Because of the "segmentation fault on more than 10 threads" bug, the system is asked via omp_get_max_threads() what the maximum numbers of threads are. If this value is larger than 10, then the maximum number of threads used for the calculation is fixed at 10 to prevent the "segmentation fault" bug. Once this issue is fixed, this can be removed.
In a next step, the input parameters for the Decayer are printed to std::ccout.
If the number of events is not a multiple of the chunkSize, then the number of remainder is calculated from the modulo. The number of maximum chunks is then derived from the ratio (events-remainder)/chunkSize.
For the Monte-Carlo decay, a unsigned int randomSeed[12] array is initialized.
Now a ProgressBar object is generated from Progressbar.h, initialized with numInChunk, which ist the number of decays in the current chunk.
At first the parameters needed to be initialized for the old Sapphire code are obtained from the SapphireInput object passed by reference to the Module_Decayer::Run() method.
Because of the "segmentation fault on more than 10 threads" bug, the system is asked via omp_get_max_threads() what the maximum numbers of threads are. If this value is larger than 10, then the maximum number of threads used for the calculation is fixed at 10 to prevent the "segmentation fault" bug. Once this issue is fixed, this can be removed.
In a next step, the input parameters for the Decayer are printed to std::ccout.
If the number of events is not a multiple of the chunkSize, then the number of remainder is calculated from the modulo. The number of maximum chunks is then derived from the ratio (events-remainder)/chunkSize.
For the Monte-Carlo decay, a unsigned int randomSeed[12] array is initialized.
Now a ProgressBar object is generated from Progressbar.h, initialized with numInChunk, which ist the number of decays in the current chunk.
References DecayResults::AddResults(), atomicNumberIntFromString(), SapphireInput::ChunkSize(), DecayController::Decay(), DecayController::DecayProducts(), SapphireInput::Events(), SapphireInput::HighEnergy(), SapphireInput::Isotope(), SapphireInput::LowEnergy(), massNumberIntFromString(), SapphireInput::Parity(), SapphireInput::PreEq(), DecayController::PrintDecays(), randomSeed, Decayer::SetCrossSection(), SapphireInput::Spin(), ProgressBar::start(), SapphireInput::Suffix(), and ProgressBar::update().
Referenced by Go().