Sapphire: /home/pscholz/SAPPHIRE/coul/src/complex_functions.cpp File Reference
complex_functions.cpp File Reference
#include "complex_functions.H"
Functions
std::complex< double > expm1 (const std::complex< double > &z)
std::complex< double > log1p (const std::complex< double > &z)
std::complex< double > log_Gamma (const std::complex< double > &z)
std::complex< double > sigma_l_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_Cl_eta_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_AS_calc (const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_CFa_calc (const bool is_it_normalized, const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_CFb_calc (const bool is_it_normalized, const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > sin_chi_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > exp_I_omega_chi_calc (const int omega, const std::complex< double > &l, const std::complex< double > &eta)
Function Documentation
exp_I_omega_chi_calc()
std::complex<double> exp_I_omega_chi_calc (const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References sigma_l_calc(), and sin_chi_calc().
expm1()
std::complex<double> expm1 (const std::complex< double > & z)
Referenced by log_cut_constant_AS_calc(), and log_cut_constant_CFa_calc().
log1p()
std::complex<double> log1p (const std::complex< double > & z)
Referenced by log_cut_constant_AS_calc(), and log_cut_constant_CFa_calc().
log_Cl_eta_calc()
std::complex<double> log_Cl_eta_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Gamma().
Referenced by log_cut_constant_CFa_calc(), log_cut_constant_CFb_calc(), and sin_chi_calc().
log_cut_constant_AS_calc()
std::complex<double> log_cut_constant_AS_calc (const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References expm1(), and log1p().
log_cut_constant_CFa_calc()
std::complex<double> log_cut_constant_CFa_calc (const bool is_it_normalized, const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References expm1(), log1p(), and log_Cl_eta_calc().
log_cut_constant_CFb_calc()
std::complex<double> log_cut_constant_CFb_calc (const bool is_it_normalized, const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References log_Cl_eta_calc().
log_Gamma()
std::complex<double> log_Gamma (const std::complex< double > & z)
Referenced by log_Cl_eta_calc(), and sigma_l_calc().
sigma_l_calc()
std::complex<double> sigma_l_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Gamma().
Referenced by exp_I_omega_chi_calc().
sin_chi_calc()
std::complex<double> sin_chi_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Cl_eta_calc().
Referenced by exp_I_omega_chi_calc().