Sapphire: KopeckyUhlGSF Class Reference
KopeckyUhlGSF Class Reference
#include <KopeckyUhlGSF.h>
Public Member Functions
KopeckyUhlGSF (int, int, double, int, double, int, double, double, double, double, TransmissionFunc *, LevelDensity *, double)
double CalcStrengthFunction (double)
Public Member Functions inherited from GammaTransmissionFunc
GammaTransmissionFunc (int, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
virtual ~GammaTransmissionFunc ()
bool IsValid ()
double operator() (double)
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Private Member Functions
double CalcEnergyDependentWidth (double, int)
double CalcKUTempSqrd (double)
Private Attributes
LevelDensity * levelDensity_
double compoundE_
double levelDenParam_
Additional Inherited Members
Static Public Member Functions inherited from GammaTransmissionFunc
static GammaTransmissionFunc * CreateGammaTransmissionFunc (int, int, double, int, double, int, double, LevelDensity *, double, double, double, TransmissionFunc *, double)
static void InitializeGDRParameters (std::string)
static void SetEGDRType (int)
static void SetPorterThomas (bool)
Protected Attributes inherited from GammaTransmissionFunc
GDRParameters gdrParameters_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Static Protected Attributes inherited from GammaTransmissionFunc
static GDRTable gdrTable_
static int egdrType_
static const int mgdrType_ =0
static const int egqrType_ =0
static bool porterThomas_
Constructor & Destructor Documentation
KopeckyUhlGSF()
KopeckyUhlGSF::KopeckyUhlGSF (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous, LevelDensity * levelDensity, double compoundE)
References LevelDensity::backshift_, LevelDensity::CalcDensityParam(), levelDenParam_, levelDensity_, and NuclearMass::QValue().
Member Function Documentation
CalcEnergyDependentWidth()
double KopeckyUhlGSF::CalcEnergyDependentWidth (double energy, int which) private
References CalcKUTempSqrd(), GDRParameters::E_, GammaTransmissionFunc::gdrParameters_, pi, and GDRParameters::W_.
Referenced by CalcStrengthFunction().
CalcKUTempSqrd()
double KopeckyUhlGSF::CalcKUTempSqrd (double energy) private
References LevelDensity::backshift_, compoundE_, levelDenParam_, and levelDensity_.
Referenced by CalcEnergyDependentWidth(), and CalcStrengthFunction().
CalcStrengthFunction()
double KopeckyUhlGSF::CalcStrengthFunction (double energy) virtual
Implements GammaTransmissionFunc.
References CalcEnergyDependentWidth(), CalcKUTempSqrd(), GDRParameters::E_, GammaTransmissionFunc::gdrParameters_, GDRParameters::kSigmaGamma_, pi, and GDRParameters::W_.
Member Data Documentation
compoundE_
double KopeckyUhlGSF::compoundE_ private
Referenced by CalcKUTempSqrd().
levelDenParam_
double KopeckyUhlGSF::levelDenParam_ private
Referenced by CalcKUTempSqrd(), and KopeckyUhlGSF().
levelDensity_
LevelDensity* KopeckyUhlGSF::levelDensity_ private
Referenced by CalcKUTempSqrd(), and KopeckyUhlGSF().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/KopeckyUhlGSF.h
/home/pscholz/SAPPHIRE/src/KopeckyUhlGSF.cpp