Sapphire: Timer Class Reference
Timer Class Reference
Used to time how intervals in code.
#include <Timer.h>
Public Member Functions
Timer ()
void start ()
Start the timer. Throws an exception if timer was already running.
double stop ()
double accumulated ()
double lap ()
void reset ()
Private Types
typedef std::chrono::high_resolution_clock clock
typedef std::chrono::duration< double, std::ratio< 1 > > second
Private Attributes
std::chrono::time_point< clock > start_time
Last time the timer was started.
double accumulated_time
Accumulated running time since creation.
bool running
True when the timer is running.
Detailed Description
Used to time how intervals in code.
Such as how long it takes a given function to run, or how long I/O has taken.
Member Typedef Documentation
clock
typedef std::chrono::high_resolution_clock Timer::clock private
second
typedef std::chrono::duration<double, std::ratio<1> > Timer::second private
Constructor & Destructor Documentation
Timer()
Timer::Timer () inline
Member Function Documentation
accumulated()
double Timer::accumulated () inline
Returns the timer's accumulated time. Throws an exception if the timer is running.
References accumulated_time.
Referenced by ProgressBar::stop(), and ProgressBar::time_it_took().
lap()
double Timer::lap () inline
Returns the time between when the timer was started and the current moment. Throws an exception if the timer is not running.
References start_time.
Referenced by stop(), and ProgressBar::update().
reset()
void Timer::reset () inline
Stops the timer and resets its accumulated time. No exceptions are thrown ever.
start()
void Timer::start () inline
Start the timer. Throws an exception if timer was already running.
Referenced by ProgressBar::start().
stop()
double Timer::stop () inline
Stop the timer. Throws an exception if timer was already stopped. Calling this adds to the timer's accumulated time.
Returns
The accumulated time in seconds.
References accumulated_time, and lap().
Referenced by ProgressBar::stop().
Member Data Documentation
accumulated_time
double Timer::accumulated_time private
Accumulated running time since creation.
Referenced by accumulated(), and stop().
running
bool Timer::running private
True when the timer is running.
start_time
std::chrono::time_point<clock> Timer::start_time private
Last time the timer was started.
Referenced by lap().
The documentation for this class was generated from the following file:
/home/pscholz/SAPPHIRE/include/Timer.h