Sapphire: CrossSection Class Reference
CrossSection Class Reference
#include <CrossSection.h>
Public Member Functions
CrossSection (int, int, int, std::string, bool, int entranceState=0, std::vector< int > exitStates=std::vector< int >(4,-1))
bool IsValid () const
void Calculate ()
void PrintCrossSections ()
void PrintTransmissionTerms ()
std::pair< double, double > CalcAverageSWaveResWidth ()
std::pair< double, double > CalcAveragePWaveResWidth ()
std::pair< double, double > CalcAverageDWaveResWidth ()
void CalculateReactionRates (bool)
void PrintReactionRates (bool)
Static Public Member Functions
static void SetResidualGamma (bool residual)
static void SetResidualNeutron (bool residual)
static void SetResidualProton (bool residual)
static void SetResidualAlpha (bool residual)
static void SetCalculateGammaCutoff (bool calc)
static void CreateTempVector ()
static void CreateMACSEnergiesVector ()
Constructor & Destructor Documentation
CrossSection::CrossSection (int Z, int A, int pType, std::string energyFile, bool forRates, int entranceState = 0, std::vector< int > exitStates = std::vector<int>(4,-1))
References Level::energy_, NuclearLevels::FindLevels(), hbarc, Level::J_, pi, Level::Pi_, NuclearMass::QValue(), and uconv.
Member Function Documentation
std::pair< double, double > CrossSection::CalcAverageDWaveResWidth ()
References pi.
Referenced by main().
std::pair< double, double > CrossSection::CalcAveragePWaveResWidth ()
References pi.
Referenced by main().
std::pair< double, double > CrossSection::CalcAverageSWaveResWidth ()
References pi.
Referenced by main().
void CrossSection::Calculate ()
References TransitionRateFunc::SetGammaCutoffEnergy().
Referenced by main().
void CrossSection::CalculateReactionRates (bool macs)
References avagadroNum, boltzConst, gsl_reactionrate_integrand(), lightSpeedInCmPerS, pi, and uconv.
Referenced by main().
void CrossSection::CreateMACSEnergiesVector () static
Referenced by Initialize().
void CrossSection::CreateTempVector () static
Referenced by Initialize().
bool CrossSection::IsValid () const inline
Referenced by main().
void CrossSection::PrintCrossSections ()
References NuclearMass::FindElement().
Referenced by main().
void CrossSection::PrintReactionRates (bool macs)
References NuclearMass::FindElement().
Referenced by main().
void CrossSection::PrintTransmissionTerms ()
References NuclearMass::FindElement().
Referenced by main().
static void CrossSection::SetCalculateGammaCutoff (bool calc) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
static void CrossSection::SetResidualAlpha (bool residual) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
static void CrossSection::SetResidualGamma (bool residual) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
static void CrossSection::SetResidualNeutron (bool residual) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
static void CrossSection::SetResidualProton (bool residual) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
The documentation for this class was generated from the following files:
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/include/CrossSection.h
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/CrossSection.cpp
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/Setup.cpp