Sapphire: ProgressBar Class Reference
ProgressBar Class Reference
#include <Progressbar.h>
Public Member Functions
void start (uint32_t total_work)
Start/reset the progress bar.
void update (uint32_t work_done0)
Update the visible progress bar, but only if enough work has been done.
ProgressBar & operator++ ()
Increment by one the work done and update the progress bar.
double stop ()
double time_it_took ()
uint32_t cellsProcessed () const
Private Member Functions
void clearConsoleLine () const
Clear current line on console so a new progress bar can be written.
Private Attributes
uint32_t total_work
Total work to be accomplished.
uint32_t next_update
Next point to update the visible progress bar.
uint32_t call_diff
Interval between updates in work units.
uint32_t work_done
uint16_t old_percent
Old percentage value (aka: should we update the progress bar) TODO: Maybe that we do not need this.
Timer timer
Used for generating ETA.
Member Function Documentation
cellsProcessed()
uint32_t ProgressBar::cellsProcessed () const inline
References work_done.
clearConsoleLine()
void ProgressBar::clearConsoleLine () const inline private
Clear current line on console so a new progress bar can be written.
Referenced by start(), and stop().
operator++()
ProgressBar& ProgressBar::operator++ () inline
Increment by one the work done and update the progress bar.
References update().
start()
void ProgressBar::start (uint32_t total_work) inline
Start/reset the progress bar.
Parameters
total_work The amount of work to be completed, usually specified in cells.
References clearConsoleLine(), Timer::start(), and total_work.
Referenced by Module_OldSapphire::oldSapphire(), and Module_Decayer::Run().
stop()
double ProgressBar::stop () inline
Stop the progress bar. Throws an exception if it wasn't started.
Returns
The number of seconds the progress bar was running.
References Timer::accumulated(), clearConsoleLine(), and Timer::stop().
time_it_took()
double ProgressBar::time_it_took () inline
Returns
Return the time the progress bar ran for.
References Timer::accumulated().
update()
void ProgressBar::update (uint32_t work_done0) inline
Update the visible progress bar, but only if enough work has been done.
Define the global NOPROGRESS flag to prevent this from having an effect. Doing so may speed up the program's execution.
References call_diff, Timer::lap(), and total_work.
Referenced by Module_OldSapphire::oldSapphire(), operator++(), and Module_Decayer::Run().
Member Data Documentation
call_diff
uint32_t ProgressBar::call_diff private
Interval between updates in work units.
Referenced by update().
next_update
uint32_t ProgressBar::next_update private
Next point to update the visible progress bar.
old_percent
uint16_t ProgressBar::old_percent private
Old percentage value (aka: should we update the progress bar) TODO: Maybe that we do not need this.
timer
Timer ProgressBar::timer private
Used for generating ETA.
total_work
uint32_t ProgressBar::total_work private
Total work to be accomplished.
Referenced by start(), and update().
work_done
uint32_t ProgressBar::work_done private
Referenced by cellsProcessed().
The documentation for this class was generated from the following file:
/home/pscholz/SAPPHIRE/include/Progressbar.h