Sapphire: CoulFunc Class Reference
CoulFunc Class Reference
#include <CoulFunc.h>
Classes
struct DEShiftParams
Public Member Functions
CoulFunc (int z1, int z2, double redmass, bool useGSLFunctions)
int z1 () const
int z2 () const
double redmass () const
int lLast () const
double radiusLast () const
double energyLast () const
struct CoulWaves coulLast () const
void setLast (int, double, double, CoulWaves)
CoulWaves operator() (int, double, double)
double Penetrability (int, double, double)
double PEShift (int, double, double)
double PEShift_dE (int, double, double)
Static Public Member Functions
static void GSLErrorHandler (const char *, const char *, int, int)
Private Types
typedef struct CoulFunc::DEShiftParams DEShiftParams
Static Private Member Functions
static double thisPEShift (double, void *)
Private Attributes
DEShiftParams dEShiftParams_
bool useGSLFunctions_
int z1_
int z2_
int lLast_
double redmass_
double radiusLast_
double energyLast_
struct CoulWaves coulLast_
Member Typedef Documentation
DEShiftParams
typedef struct CoulFunc::DEShiftParams CoulFunc::DEShiftParams private
Constructor & Destructor Documentation
CoulFunc()
CoulFunc::CoulFunc (int z1, int z2, double redmass, bool useGSLFunctions)
References CoulFunc::DEShiftParams::coulFunc, coulLast_, dEShiftParams_, CoulWaves::dF, CoulWaves::dG, energyLast_, CoulWaves::F, CoulWaves::G, lLast_, and radiusLast_.
Member Function Documentation
coulLast()
struct CoulWaves CoulFunc::coulLast () const
Returns the last Coulomb functions which were calculated.
References coulLast_.
Referenced by operator()().
energyLast()
double CoulFunc::energyLast () const
Returns the last energy value at which the Coulomb functions were calculated.
References energyLast_.
Referenced by operator()().
GSLErrorHandler()
void CoulFunc::GSLErrorHandler (const char * reason, const char * file, int line, int errorCode) static
Referenced by Initialize().
lLast()
int CoulFunc::lLast () const
Returns the last orbital angular momentum value at which the Coulomb functions were calculated.
References lLast_.
Referenced by operator()(), and setLast().
operator()()
CoulWaves CoulFunc::operator() (int l, double radius, double energy)
The parenthesis operator is defined to make the class instance callable as a function. The orbital angular momentum, radius, and energy in the center of mass system are the dependent variables. The function returns the Coulomb waves.
References coulLast(), CoulWaves::dF, CoulWaves::dG, energyLast(), CoulWaves::F, fstruc, CoulWaves::G, hbarc, lLast(), radiusLast(), redmass(), uconv, useGSLFunctions_, z1(), and z2().
Referenced by Penetrability(), and PEShift().
Penetrability()
double CoulFunc::Penetrability (int l, double radius, double energy)
Returns the penetrability as a function of orbital angular momentum, radius, and energy in the center of mass system.
References CoulWaves::F, CoulWaves::G, hbarc, operator()(), redmass(), and uconv.
Referenced by EquivSquareWell::CalcTransmission().
PEShift()
double CoulFunc::PEShift (int l, double radius, double energy)
Returns the positive energy shift function a function of orbital angular momentum, radius, and energy in the center of mass system.
References CoulWaves::dF, CoulWaves::dG, CoulWaves::F, CoulWaves::G, hbarc, operator()(), redmass(), and uconv.
Referenced by thisPEShift().
PEShift_dE()
double CoulFunc::PEShift_dE (int l, double radius, double energy)
Returns the energy derivative of the shift function a function of orbital angular momentum, radius, and energy in the center of mass system.
References dEShiftParams_, CoulWaves::F, CoulFunc::DEShiftParams::lValue, CoulFunc::DEShiftParams::radius, and thisPEShift().
radiusLast()
double CoulFunc::radiusLast () const
Returns the last radius value at which the Coulomb functions were calculated.
References radiusLast_.
Referenced by operator()().
redmass()
double CoulFunc::redmass () const
Returns the reduced mass of the particle pair.
References redmass_.
Referenced by operator()(), Penetrability(), and PEShift().
setLast()
void CoulFunc::setLast (int lLast, double rLast, double eLast, CoulWaves coulLast)
Sets the last calculated Coulomb waves and the values for which they were calculated.
References coulLast_, CoulWaves::dF, CoulWaves::dG, energyLast_, CoulWaves::F, CoulWaves::G, lLast(), lLast_, and radiusLast_.
thisPEShift()
double CoulFunc::thisPEShift (double x, void * p) static private
References CoulFunc::DEShiftParams::coulFunc, CoulFunc::DEShiftParams::lValue, PEShift(), and CoulFunc::DEShiftParams::radius.
Referenced by PEShift_dE().
z1()
int CoulFunc::z1 () const
Returns the atomic number of the first particle in the pair.
References z1_.
Referenced by operator()().
z2()
int CoulFunc::z2 () const
Returns the atomic number of the second particle in the pair.
References z2_.
Referenced by operator()().
Member Data Documentation
coulLast_
struct CoulWaves CoulFunc::coulLast_ private
Referenced by CoulFunc(), coulLast(), and setLast().
dEShiftParams_
DEShiftParams CoulFunc::dEShiftParams_ private
Referenced by CoulFunc(), and PEShift_dE().
energyLast_
double CoulFunc::energyLast_ private
Referenced by CoulFunc(), energyLast(), and setLast().
lLast_
int CoulFunc::lLast_ private
Referenced by CoulFunc(), lLast(), and setLast().
radiusLast_
double CoulFunc::radiusLast_ private
Referenced by CoulFunc(), radiusLast(), and setLast().
redmass_
double CoulFunc::redmass_ private
Referenced by redmass().
useGSLFunctions_
bool CoulFunc::useGSLFunctions_ private
Referenced by operator()().
z1_
int CoulFunc::z1_ private
Referenced by z1().
z2_
int CoulFunc::z2_ private
Referenced by z2().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/CoulFunc.h
/home/pscholz/SAPPHIRE/src/CoulFunc.cpp