Sapphire: RauscherLevelDensity Class Reference
RauscherLevelDensity Class Reference
#include <RauscherLevelDensity.h>
Public Member Functions
RauscherLevelDensity (int Z, int A, double J)
~RauscherLevelDensity ()
void CalcBackShift ()
double CalcDensityParam (double)
double CalcNuclearTemp (double)
Public Member Functions inherited from LevelDensity
LevelDensity (int Z, int A, double J)
virtual ~LevelDensity ()
double operator() (double)
double TotalLevelDensity (double)
Private Attributes
double aTilda_
double microEnergyCorr_
Static Private Attributes
static constexpr double alpha_ = 0.1337
static constexpr double beta_ = -0.06571
static constexpr double gamma_ = 0.04884
Additional Inherited Members
Protected Member Functions inherited from LevelDensity
void CalcConstantTempTerms ()
Protected Attributes inherited from LevelDensity
int Z_
int A_
double J_
double backshift_
double criticalU_
double constAngTerm_
double nuclearTemp_
double e0_
Static Protected Attributes inherited from LevelDensity
static constexpr double zeta_ = 1.0
static constexpr double r0_ = 1.25
Constructor & Destructor Documentation
RauscherLevelDensity()
RauscherLevelDensity::RauscherLevelDensity (int Z, int A, double J) inline
References alpha_, aTilda_, beta_, CalcBackShift(), LevelDensity::CalcConstantTempTerms(), NuclearMass::MicroEnergyCorr(), and microEnergyCorr_.
~RauscherLevelDensity()
RauscherLevelDensity::~RauscherLevelDensity () inline
References CalcBackShift(), CalcDensityParam(), and CalcNuclearTemp().
Member Function Documentation
CalcBackShift()
void RauscherLevelDensity::CalcBackShift () virtual
Implements LevelDensity.
References LevelDensity::A_, LevelDensity::backshift_, NuclearMass::NeutronPairingGap(), NuclearMass::ProtonPairingGap(), and LevelDensity::Z_.
Referenced by RauscherLevelDensity(), and ~RauscherLevelDensity().
CalcDensityParam()
double RauscherLevelDensity::CalcDensityParam (double u) virtual
Implements LevelDensity.
References aTilda_, gamma_, and microEnergyCorr_.
Referenced by CalcNuclearTemp(), and ~RauscherLevelDensity().
CalcNuclearTemp()
double RauscherLevelDensity::CalcNuclearTemp (double u) virtual
Implements LevelDensity.
References aTilda_, CalcDensityParam(), gamma_, and microEnergyCorr_.
Referenced by ~RauscherLevelDensity().
Member Data Documentation
alpha_
constexpr double RauscherLevelDensity::alpha_ = 0.1337 static private
Referenced by RauscherLevelDensity().
aTilda_
double RauscherLevelDensity::aTilda_ private
Referenced by CalcDensityParam(), CalcNuclearTemp(), and RauscherLevelDensity().
beta_
constexpr double RauscherLevelDensity::beta_ = -0.06571 static private
Referenced by RauscherLevelDensity().
gamma_
constexpr double RauscherLevelDensity::gamma_ = 0.04884 static private
Referenced by CalcDensityParam(), and CalcNuclearTemp().
microEnergyCorr_
double RauscherLevelDensity::microEnergyCorr_ private
Referenced by CalcDensityParam(), CalcNuclearTemp(), and RauscherLevelDensity().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/RauscherLevelDensity.h
/home/pscholz/SAPPHIRE/src/RauscherLevelDensity.cpp