Sapphire: ParticleTransmissionFunc Class Reference
ParticleTransmissionFunc Class Reference abstract
#include <ParticleTransmissionFunc.h>
Public Member Functions
ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~ParticleTransmissionFunc ()
bool IsValid ()
double operator() (double)
double operator() (double, int)
void CalcSLDependentFunctions (double, std::map< SLPair, double > &)
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Static Public Member Functions
static ParticleTransmissionFunc * CreateParticleTransmissionFunc (int, int, int, int, double, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
static void SetAlphaFormalism (int formalism)
static void SetNeutronFormalism (int formalism)
static void SetProtonFormalism (int formalism)
static void SetPorterThomas (bool)
Protected Member Functions
virtual double CalcTransmission (double, int, double)=0
Protected Attributes
int z1_
int m1_
int pType_
int parity_
double redmass_
double spin_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Static Private Attributes
static bool porterThomas_
static int alphaFormalism_
static int protonFormalism_
static int neutronFormalism_
Constructor & Destructor Documentation
ParticleTransmissionFunc()
ParticleTransmissionFunc::ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous) inline
References NuclearMass::FindMass(), and uconv.
~ParticleTransmissionFunc()
virtual ParticleTransmissionFunc::~ParticleTransmissionFunc () inline virtual
Member Function Documentation
CalcSLDependentFunctions()
void ParticleTransmissionFunc::CalcSLDependentFunctions (double energy, std::map< SLPair, double > & functions)
References CalcTransmission(), TransmissionFunc::jFinal_, TransmissionFunc::jInitial_, TransmissionFunc::maxL_, parity_, TransmissionFunc::piFinal_, TransmissionFunc::piInitial_, and spin_.
Referenced by operator()().
CalcTransmission()
virtual double ParticleTransmissionFunc::CalcTransmission (double , int , double) protected pure virtual
Implemented in EquivSquareWell, and Potential.
Referenced by CalcSLDependentFunctions().
CreateParticleTransmissionFunc()
ParticleTransmissionFunc * ParticleTransmissionFunc::CreateParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous) static
References alphaFormalism_, neutronFormalism_, and protonFormalism_.
Referenced by PreEqTransitionRateFunc::CalcParticleDecay(), and TransitionRateFunc::TransitionRateFunc().
IsValid()
bool ParticleTransmissionFunc::IsValid () inline virtual
Implements TransmissionFunc.
Referenced by PreEqTransitionRateFunc::CalcParticleDecay().
operator()() [1/2]
double ParticleTransmissionFunc::operator() (double energy) virtual
Implements TransmissionFunc.
References CalcSLDependentFunctions(), porterThomas_, TransmissionFunc::previous_, randomSeed, TransmissionFunc::totalWidthForCorrection_, TransmissionFunc::uncorrTotalWidthForCorrection_, and TransmissionFunc::uncorrTotalWidthSqrdForCorrection_.
operator()() [2/2]
double ParticleTransmissionFunc::operator() (double energy, int which)
References CalcSLDependentFunctions(), TransmissionFunc::previous_, TransmissionFunc::totalWidthForCorrection_, TransmissionFunc::uncorrTotalWidthForCorrection_, and TransmissionFunc::uncorrTotalWidthSqrdForCorrection_.
SetAlphaFormalism()
static void ParticleTransmissionFunc::SetAlphaFormalism (int formalism) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetNeutronFormalism()
static void ParticleTransmissionFunc::SetNeutronFormalism (int formalism) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetPorterThomas()
void ParticleTransmissionFunc::SetPorterThomas (bool yn) static
References porterThomas_.
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
SetProtonFormalism()
static void ParticleTransmissionFunc::SetProtonFormalism (int formalism) inline static
Referenced by Initialize(), Module_OldSapphire::parseCommandLineForOptions(), and Module_CrossSection::Run().
Member Data Documentation
alphaFormalism_
int ParticleTransmissionFunc::alphaFormalism_ static private
Referenced by CreateParticleTransmissionFunc().
m1_
int ParticleTransmissionFunc::m1_ protected
Referenced by Potential::CalcTransmission().
neutronFormalism_
int ParticleTransmissionFunc::neutronFormalism_ static private
Referenced by CreateParticleTransmissionFunc().
parity_
int ParticleTransmissionFunc::parity_ protected
Referenced by CalcSLDependentFunctions().
porterThomas_
bool ParticleTransmissionFunc::porterThomas_ static private
Referenced by operator()(), and SetPorterThomas().
protonFormalism_
int ParticleTransmissionFunc::protonFormalism_ static private
Referenced by CreateParticleTransmissionFunc().
pType_
int ParticleTransmissionFunc::pType_ protected
Referenced by EquivSquareWell::GetF(), EquivSquareWell::GetR0(), EquivSquareWell::GetR1(), and EquivSquareWell::GetV0().
redmass_
double ParticleTransmissionFunc::redmass_ protected
Referenced by EquivSquareWell::CalcTransmission(), EquivSquareWell::EquivSquareWell(), and Potential::GetRedMass().
spin_
double ParticleTransmissionFunc::spin_ protected
Referenced by CalcSLDependentFunctions().
z1_
int ParticleTransmissionFunc::z1_ protected
Referenced by EquivSquareWell::EquivSquareWell(), and Potential::GetZ1Z2().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/ParticleTransmissionFunc.h
/home/pscholz/SAPPHIRE/src/ParticleTransmissionFunc.cpp
/home/pscholz/SAPPHIRE/src/Setup.cpp