Sapphire: ParticleTransmissionFunc Class Reference
ParticleTransmissionFunc Class Reference abstract
#include <ParticleTransmissionFunc.h>
Public Member Functions
ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~ParticleTransmissionFunc ()
bool IsValid ()
double operator() (double)
double operator() (double, int)
void CalcSLDependentFunctions (double, std::map< SLPair, double > &)
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Static Public Member Functions
static ParticleTransmissionFunc * CreateParticleTransmissionFunc (int, int, int, int, double, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
static void SetAlphaFormalism (int formalism)
static void SetNeutronFormalism (int formalism)
static void SetProtonFormalism (int formalism)
static void SetPorterThomas (bool)
Protected Member Functions
virtual double CalcTransmission (double, int, double)=0
Protected Attributes
int z1_
int m1_
int pType_
int parity_
double redmass_
double spin_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Constructor & Destructor Documentation
ParticleTransmissionFunc::ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous) inline
References NuclearMass::FindMass(), m1_, TransmissionFunc::m2_, pType_, redmass_, uconv, z1_, and TransmissionFunc::z2_.
virtual ParticleTransmissionFunc::~ParticleTransmissionFunc () inline virtual
Member Function Documentation
void ParticleTransmissionFunc::CalcSLDependentFunctions (double energy, std::map< SLPair, double > & functions)
References CalcTransmission(), TransmissionFunc::jFinal_, TransmissionFunc::jInitial_, TransmissionFunc::maxL_, parity_, TransmissionFunc::piFinal_, TransmissionFunc::piInitial_, and spin_.
Referenced by operator()().
virtual double ParticleTransmissionFunc::CalcTransmission (double , int , double) protected pure virtual
Implemented in EquivSquareWell, and Potential.
Referenced by CalcSLDependentFunctions().
ParticleTransmissionFunc * ParticleTransmissionFunc::CreateParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous) static
Referenced by TransitionRateFunc::TransitionRateFunc().
bool ParticleTransmissionFunc::IsValid () inline virtual
Implements TransmissionFunc.
References pType_, and redmass_.
double ParticleTransmissionFunc::operator() (double energy) virtual
Implements TransmissionFunc.
References CalcSLDependentFunctions(), TransmissionFunc::previous_, randomSeed, TransmissionFunc::totalWidthForCorrection_, TransmissionFunc::uncorrTotalWidthForCorrection_, and TransmissionFunc::uncorrTotalWidthSqrdForCorrection_.
double ParticleTransmissionFunc::operator() (double energy, int which)
References CalcSLDependentFunctions(), TransmissionFunc::previous_, TransmissionFunc::totalWidthForCorrection_, TransmissionFunc::uncorrTotalWidthForCorrection_, and TransmissionFunc::uncorrTotalWidthSqrdForCorrection_.
static void ParticleTransmissionFunc::SetAlphaFormalism (int formalism) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
static void ParticleTransmissionFunc::SetNeutronFormalism (int formalism) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
void ParticleTransmissionFunc::SetPorterThomas (bool yn) static
Referenced by Initialize(), and parseCommandLineForOptions().
static void ParticleTransmissionFunc::SetProtonFormalism (int formalism) inline static
Referenced by Initialize(), and parseCommandLineForOptions().
Member Data Documentation
int ParticleTransmissionFunc::m1_ protected
Referenced by Potential::CalcTransmission(), and ParticleTransmissionFunc().
int ParticleTransmissionFunc::parity_ protected
Referenced by CalcSLDependentFunctions().
int ParticleTransmissionFunc::pType_ protected
Referenced by IsValid(), and ParticleTransmissionFunc().
double ParticleTransmissionFunc::redmass_ protected
Referenced by EquivSquareWell::CalcTransmission(), EquivSquareWell::EquivSquareWell(), Potential::GetRedMass(), IsValid(), and ParticleTransmissionFunc().
double ParticleTransmissionFunc::spin_ protected
Referenced by CalcSLDependentFunctions().
int ParticleTransmissionFunc::z1_ protected
Referenced by EquivSquareWell::EquivSquareWell(), Potential::GetZ1Z2(), and ParticleTransmissionFunc().
The documentation for this class was generated from the following files:
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/include/ParticleTransmissionFunc.h
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/ParticleTransmissionFunc.cpp
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/Setup.cpp