Sapphire: NuclearLevels Class Reference
NuclearLevels Class Reference
#include <NuclearLevels.h>
Static Public Member Functions
static void InitializeLevels (std::string levelsDirectory, std::string spinFile)
static void PrintLevels (int, int)
static std::vector< Level > FindLevels (int, int)
Static Private Attributes
static LevelsTable levelsTable_
Member Function Documentation
FindLevels()
std::vector< Level > NuclearLevels::FindLevels (int Z, int A) static
Referenced by CrossSection::CalcPartitionFunc(), CrossSection::CalculateEnergyGrid(), CrossSection::CheckChannels(), Decayer::Decayer(), CrossSection::FindInitialState(), CrossSection::InitializeSeperationEnergies(), and TransitionRateFunc::TransitionRateFunc().
InitializeLevels()
void NuclearLevels::InitializeLevels (std::string levelsDirectory, std::string spinFile) static
References LevelsContainer::levels_, and LevelsContainer::LevelsContainer().
Referenced by Initialize().
PrintLevels()
void NuclearLevels::PrintLevels (int Z, int A) static
Member Data Documentation
levelsTable_
LevelsTable NuclearLevels::levelsTable_ static private
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/NuclearLevels.h
/home/pscholz/SAPPHIRE/src/NuclearLevels.cpp
/home/pscholz/SAPPHIRE/src/Setup.cpp