Sapphire: NuclearMass Class Reference
NuclearMass Class Reference
#include <NuclearMass.h>
Static Public Member Functions
static void InitializeElements ()
static void InitializeMasses (std::string)
static int FindZ (std::string)
static std::string FindElement (int)
static bool FindMass (int, int, double &)
static bool MassDifference (int, int, int, int, double &)
static bool QValue (int, int, int, int, double &)
static bool NeutronPairingGap (int, int, double &)
static bool ProtonPairingGap (int, int, double &)
static bool MicroEnergyCorr (int, int, double &)
static bool HighestBoundEnergy (int, int, double &)
static double CalculateLDMMass (int, int)
Member Function Documentation
double NuclearMass::CalculateLDMMass (int Z, int A) static
Calculates liquid drop model mass based on TALYS parametrization.
References uconv.
std::string NuclearMass::FindElement (int Z) static
Referenced by DecayResults::DecayResults(), CrossSection::PrintCrossSections(), CrossSection::PrintReactionRates(), and CrossSection::PrintTransmissionTerms().
bool NuclearMass::FindMass (int Z, int A, double & M) static
References HAS_EXP_MASS, and HAS_TH_MASS.
Referenced by GammaTransmissionFunc::GammaTransmissionFunc(), MassDifference(), ParticleTransmissionFunc::ParticleTransmissionFunc(), and QValue().
int NuclearMass::FindZ (std::string element) static
Referenced by parseCommandLineForDecay(), and parseCommandLineForXS().
bool NuclearMass::HighestBoundEnergy (int Z, int A, double & energy) static
References QValue().
Referenced by TransitionRateFunc::TransitionRateFunc().
void NuclearMass::InitializeElements () static
Referenced by Initialize().
void NuclearMass::InitializeMasses (std::string filename) static
References HAS_EXP_MASS, HAS_TH_MASS, and uconv.
Referenced by Initialize().
bool NuclearMass::MassDifference (int Z1, int A1, int Z2, int A2, double & difference) static
References FindMass().
Referenced by NeutronPairingGap(), ProtonPairingGap(), and QValue().
bool NuclearMass::MicroEnergyCorr (int Z, int A, double & correction) static
Referenced by RauscherLevelDensity::RauscherLevelDensity().
bool NuclearMass::NeutronPairingGap (int Z, int A, double & pairingGap) static
References MassDifference().
Referenced by RauscherLevelDensity::CalcBackShift().
bool NuclearMass::ProtonPairingGap (int Z, int A, double & pairingGap) static
References MassDifference().
Referenced by RauscherLevelDensity::CalcBackShift().
bool NuclearMass::QValue (int Z1, int A1, int Z2, int A2, double & qValue) static
References FindMass(), and MassDifference().
Referenced by CrossSection::CrossSection(), Decayer::Decayer(), HighestBoundEnergy(), KopeckyUhlGSF::KopeckyUhlGSF(), ParticleHoleLevelDensity::ParticleHoleLevelDensity(), and PreEqDecayer::PreEqDecayer().
The documentation for this class was generated from the following files:
include/NuclearMass.h
src/NuclearMass.cpp
src/Setup.cpp