Sapphire: src/Sapphire.cpp File Reference
Sapphire.cpp File Reference
#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <algorithm>
#include "DecayController.h"
#include "NuclearMass.h"
#include "DecayResults.h"
#include "CrossSection.h"
#include "omp.h"
#include "TransitionRateFunc.h"
#include "ParticleTransmissionFunc.h"
#include "GammaTransmissionFunc.h"
Classes
struct EntrancePairs
Typedefs
typedef struct EntrancePairs EntrancePairs
Functions
void Initialize ()
void printHelp ()
void parseCommandLineForOptions (std::vector< std::string > &args, int &suffixNo, bool &preEq, int &numPiParticles, int &numPiHoles, int &numNuParticles, int &numNuHoles, bool &calcAverageWidth, bool &calcRates, bool &asciiIn, std::string &inFile, int &entranceState, std::vector< int > &exitStates, bool &printTrans)
bool parseCommandLineForDecay (std::vector< std::string > &args, int &Z, int &A, double &J, int &Pi, double &lowEnergy, double &highEnergy, int &events)
bool parseCommandLineForXS (std::vector< std::string > &args, int &Z, int &A, int &pType, std::string &energyFile, bool asciiIn)
int main (int argc, char *argv[])
Variables
unsigned int randomSeed [12]
Typedef Documentation
typedef struct EntrancePairs EntrancePairs
Function Documentation
void Initialize ()
... text ...
References CrossSection::CreateMACSEnergiesVector(), CrossSection::CreateTempVector(), CoulFunc::GSLErrorHandler(), NuclearMass::InitializeElements(), GammaTransmissionFunc::InitializeGDRParameters(), NuclearLevels::InitializeLevels(), NuclearMass::InitializeMasses(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), Decayer::SetCrossSection(), PreEqDecayer::SetCrossSection(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), Decayer::SetMaxL(), PreEqDecayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), and CrossSection::SetResidualProton().
Referenced by main().
int main (int argc, char * argv[])
References DecayResults::AddResults(), CrossSection::CalcAverageDWaveResWidth(), CrossSection::CalcAveragePWaveResWidth(), CrossSection::CalcAverageSWaveResWidth(), CrossSection::Calculate(), CrossSection::CalculateReactionRates(), DecayController::Decay(), DecayController::DecayProducts(), Initialize(), CrossSection::IsValid(), parseCommandLineForDecay(), parseCommandLineForOptions(), parseCommandLineForXS(), CrossSection::PrintCrossSections(), DecayController::PrintDecays(), printHelp(), CrossSection::PrintReactionRates(), CrossSection::PrintTransmissionTerms(), randomSeed, and Decayer::SetCrossSection().
bool parseCommandLineForDecay (std::vector< std::string > & args, int & Z, int & A, double & J, int & Pi, double & lowEnergy, double & highEnergy, int & events)
References NuclearMass::FindZ().
Referenced by main().
void parseCommandLineForOptions (std::vector< std::string > & args, int & suffixNo, bool & preEq, int & numPiParticles, int & numPiHoles, int & numNuParticles, int & numNuHoles, bool & calcAverageWidth, bool & calcRates, bool & asciiIn, std::string & inFile, int & entranceState, std::vector< int > & exitStates, bool & printTrans)
References TransitionRateFunc::GetGammaCutoffEnergy(), Decayer::GetMaxL(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), Decayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), and CrossSection::SetResidualProton().
Referenced by main().
bool parseCommandLineForXS (std::vector< std::string > & args, int & Z, int & A, int & pType, std::string & energyFile, bool asciiIn)
References NuclearMass::FindZ().
Referenced by main().
void printHelp ()
Referenced by main().
Variable Documentation
unsigned int randomSeed[12]
Referenced by Decayer::Decay(), PreEqDecayer::Decay(), main(), ParticleTransmissionFunc::operator()(), and GammaTransmissionFunc::operator()().