Sapphire: CoulFunc Class Reference
CoulFunc Class Reference
#include <CoulFunc.h>
Public Member Functions
CoulFunc (int z1, int z2, double redmass, bool useGSLFunctions)
int z1 () const
int z2 () const
double redmass () const
int lLast () const
double radiusLast () const
double energyLast () const
struct CoulWaves coulLast () const
void setLast (int, double, double, CoulWaves)
CoulWaves operator() (int, double, double)
double Penetrability (int, double, double)
double PEShift (int, double, double)
double PEShift_dE (int, double, double)
Static Public Member Functions
static void GSLErrorHandler (const char *, const char *, int, int)
Constructor & Destructor Documentation
CoulFunc::CoulFunc (int z1, int z2, double redmass, bool useGSLFunctions)
References CoulWaves::dF, CoulWaves::dG, CoulWaves::F, and CoulWaves::G.
Member Function Documentation
struct CoulWaves CoulFunc::coulLast () const
Returns the last Coulomb functions which were calculated.
Referenced by operator()().
double CoulFunc::energyLast () const
Returns the last energy value at which the Coulomb functions were calculated.
Referenced by operator()().
void CoulFunc::GSLErrorHandler (const char * reason, const char * file, int line, int errorCode) static
Referenced by Initialize().
int CoulFunc::lLast () const
Returns the last orbital angular momentum value at which the Coulomb functions were calculated.
Referenced by operator()(), and setLast().
CoulWaves CoulFunc::operator() (int l, double radius, double energy)
The parenthesis operator is defined to make the class instance callable as a function. The orbital angular momentum, radius, and energy in the center of mass system are the dependent variables. The function returns the Coulomb waves.
References coulLast(), CoulWaves::dF, CoulWaves::dG, energyLast(), CoulWaves::F, Coulomb_wave_functions::F_dF(), fstruc, CoulWaves::G, Coulomb_wave_functions::G_dG(), hbarc, lLast(), radiusLast(), redmass(), uconv, z1(), and z2().
Referenced by Penetrability(), and PEShift().
double CoulFunc::Penetrability (int l, double radius, double energy)
Returns the penetrability as a function of orbital angular momentum, radius, and energy in the center of mass system.
References CoulWaves::F, CoulWaves::G, hbarc, operator()(), redmass(), and uconv.
Referenced by EquivSquareWell::CalcTransmission().
double CoulFunc::PEShift (int l, double radius, double energy)
Returns the positive energy shift function a function of orbital angular momentum, radius, and energy in the center of mass system.
References CoulWaves::dF, CoulWaves::dG, CoulWaves::F, CoulWaves::G, hbarc, operator()(), redmass(), and uconv.
double CoulFunc::PEShift_dE (int l, double radius, double energy)
Returns the energy derivative of the shift function a function of orbital angular momentum, radius, and energy in the center of mass system.
References CoulWaves::F.
double CoulFunc::radiusLast () const
Returns the last radius value at which the Coulomb functions were calculated.
Referenced by operator()().
double CoulFunc::redmass () const
Returns the reduced mass of the particle pair.
Referenced by operator()(), Penetrability(), and PEShift().
void CoulFunc::setLast (int lLast, double rLast, double eLast, CoulWaves coulLast)
Sets the last calculated Coulomb waves and the values for which they were calculated.
References CoulWaves::dF, CoulWaves::dG, CoulWaves::F, CoulWaves::G, and lLast().
int CoulFunc::z1 () const
Returns the atomic number of the first particle in the pair.
Referenced by operator()().
int CoulFunc::z2 () const
Returns the atomic number of the second particle in the pair.
Referenced by operator()().
The documentation for this class was generated from the following files:
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/include/CoulFunc.h
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/CoulFunc.cpp