Sapphire: Potential Class Reference
Potential Class Reference abstract
#include <Potential.h>
Public Member Functions
Potential (int, int, int, int, double, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
~Potential ()
int GetZ1Z2 () const
double GetBoundaryRadius () const
double GetRedMass () const
double GetRMax () const
virtual std::complex< double > Calculate (double, int, double, double, double) const =0
std::complex< double > CalcBeta (double, int, double, double, double) const
double CalcTransmission (double, int, double)
void NormalizeInternally (std::vector< std::complex< double > > &, double) const
void NormalizeOverAllSpace (std::vector< std::complex< double > > &, double) const
std::vector< std::complex
< double > > Solve (double, int, double, double, double) const
Public Member Functions inherited from ParticleTransmissionFunc
ParticleTransmissionFunc (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~ParticleTransmissionFunc ()
bool IsValid ()
double operator() (double)
double operator() (double, int)
void CalcSLDependentFunctions (double, std::map< SLPair, double > &)
Public Member Functions inherited from TransmissionFunc
TransmissionFunc (int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc *previous)
virtual ~TransmissionFunc ()
Protected Attributes
CoulFunc * coulFunc_
double boundaryRadius_
double coulombRadius_
Protected Attributes inherited from ParticleTransmissionFunc
int z1_
int m1_
int pType_
int parity_
double redmass_
double spin_
Protected Attributes inherited from TransmissionFunc
int z2_
int m2_
int piInitial_
int piFinal_
double jInitial_
double jFinal_
double maxL_
double totalWidthForCorrection_
double uncorrTotalWidthForCorrection_
double uncorrTotalWidthSqrdForCorrection_
TransmissionFunc * previous_
Additional Inherited Members
Static Public Member Functions inherited from ParticleTransmissionFunc
static ParticleTransmissionFunc * CreateParticleTransmissionFunc (int, int, int, int, double, int, double, int, double, int, double, double, double, double, TransmissionFunc *)
static void SetAlphaFormalism (int formalism)
static void SetNeutronFormalism (int formalism)
static void SetProtonFormalism (int formalism)
static void SetPorterThomas (bool)
Constructor & Destructor Documentation
Potential::Potential (int z1, int m1, int z2, int m2, double jInitial, int piInitial, double jFinal, int piFinal, double spin, int parity, double maxL, double totalWidthForCorrection, double uncorrTotalWidthForCorrection, double uncorrTotalWidthSqrdForCorrection, TransmissionFunc * previous)
References coulFunc_, and GetRedMass().
Potential::~Potential ()
References coulFunc_.
Member Function Documentation
std::complex< double > Potential::CalcBeta (double energy, int l, double s, double j, double rStep) const
References GetBoundaryRadius(), NormalizeInternally(), and Solve().
Referenced by CalcTransmission().
double Potential::CalcTransmission (double s, int l, double energy) virtual
Implements ParticleTransmissionFunc.
References CalcBeta(), coulFunc_, CoulWaves::dF, CoulWaves::dG, CoulWaves::F, CoulWaves::G, GetBoundaryRadius(), GetRedMass(), hbarc, TransmissionFunc::jInitial_, ParticleTransmissionFunc::m1_, and uconv.
virtual std::complex<double> Potential::Calculate (double , int , double , double , double) const pure virtual
Implemented in JLMPotential, and McFaddenSatchlerPotential.
Referenced by Solve().
double Potential::GetBoundaryRadius () const inline
References boundaryRadius_.
Referenced by CalcBeta(), CalcTransmission(), NormalizeInternally(), and Solve().
double Potential::GetRedMass () const inline
References ParticleTransmissionFunc::redmass_.
Referenced by CalcTransmission(), Potential(), and Solve().
double Potential::GetRMax () const inline
References boundaryRadius_.
int Potential::GetZ1Z2 () const inline
References ParticleTransmissionFunc::z1_, and TransmissionFunc::z2_.
Referenced by JLMPotential::Calculate(), and McFaddenSatchlerPotential::Calculate().
void Potential::NormalizeInternally (std::vector< std::complex< double > > & waveFunction, double rStep) const
References GetBoundaryRadius().
Referenced by CalcBeta().
void Potential::NormalizeOverAllSpace (std::vector< std::complex< double > > & waveFunction, double rStep) const
std::vector< std::complex< double > > Potential::Solve (double energy, int L, double S, double J, double rStep) const
References Calculate(), GetBoundaryRadius(), GetRedMass(), hbarc, and uconv.
Referenced by CalcBeta().
Member Data Documentation
double Potential::boundaryRadius_ protected
Referenced by GetBoundaryRadius(), GetRMax(), JLMPotential::JLMPotential(), and McFaddenSatchlerPotential::McFaddenSatchlerPotential().
CoulFunc* Potential::coulFunc_ protected
Referenced by CalcTransmission(), Potential(), and ~Potential().
double Potential::coulombRadius_ protected
Referenced by JLMPotential::Calculate(), McFaddenSatchlerPotential::Calculate(), JLMPotential::JLMPotential(), and McFaddenSatchlerPotential::McFaddenSatchlerPotential().
The documentation for this class was generated from the following files:
include/Potential.h
src/Potential.cpp