Sapphire: /home/pscholz/SAPPHIRE/src/Setup.cpp File Reference
Setup.cpp File Reference
#include "NuclearMass.h"
#include "GammaTransmissionFunc.h"
#include "NuclearLevels.h"
#include "Decayer.h"
#include "Sapphire_config.h"
#include "TransitionRateFunc.h"
#include "CrossSection.h"
#include "PreEqDecayer.h"
#include "ParticleTransmissionFunc.h"
#include "CoulFunc.h"
#include <iostream>
#include <gsl/gsl_errno.h>
Functions
void Initialize ()
First Function which is called in the Sapphire main() in Sapphire.cpp. Setting default parameters.
Function Documentation
Initialize()
void Initialize ()
First Function which is called in the Sapphire main() in Sapphire.cpp. Setting default parameters.
Now there are new includes which differ from the original version
References CrossSection::CreateMACSEnergiesVector(), CrossSection::CreateTempVector(), CoulFunc::GSLErrorHandler(), NuclearMass::InitializeElements(), GammaTransmissionFunc::InitializeGDRParameters(), NuclearLevels::InitializeLevels(), NuclearMass::InitializeMasses(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), PreEqDecayer::SetCrossSection(), Decayer::SetCrossSection(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), PreEqDecayer::SetMaxL(), Decayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), CrossSection::SetResidualProton(), and sourceDirectory().
Referenced by main().