Sapphire: coul/include/complex_functions.H File Reference
complex_functions.H File Reference
#include <complex>
#include <iostream>
#include <cstdlib>
Macros
#define SIGN(a) (((a) < 0) ? (-1) : (1))
Functions
double inf_norm (const std::complex< double > &z)
bool isfinite (const std::complex< double > &z)
std::complex< double > operator+ (const std::complex< double > &z, const int n)
std::complex< double > operator- (const std::complex< double > &z, const int n)
std::complex< double > operator* (const std::complex< double > &z, const int n)
std::complex< double > operator/ (const std::complex< double > &z, const int n)
std::complex< double > operator+ (const int n, const std::complex< double > &z)
std::complex< double > operator- (const int n, const std::complex< double > &z)
std::complex< double > operator* (const int n, const std::complex< double > &z)
std::complex< double > operator/ (const int n, const std::complex< double > &z)
std::complex< double > operator+ (const std::complex< double > &z, const unsigned int n)
std::complex< double > operator- (const std::complex< double > &z, const unsigned int n)
std::complex< double > operator* (const std::complex< double > &z, const unsigned int n)
std::complex< double > operator/ (const std::complex< double > &z, const unsigned int n)
std::complex< double > operator+ (const unsigned int n, const std::complex< double > &z)
std::complex< double > operator- (const unsigned int n, const std::complex< double > &z)
std::complex< double > operator* (const unsigned int n, const std::complex< double > &z)
std::complex< double > operator/ (const unsigned int n, const std::complex< double > &z)
bool operator== (const std::complex< double > &z, const int n)
bool operator!= (const std::complex< double > &z, const int n)
bool operator== (const int n, const std::complex< double > &z)
bool operator!= (const int n, const std::complex< double > &z)
bool operator== (const std::complex< double > &z, const unsigned int n)
bool operator!= (const std::complex< double > &z, const unsigned int n)
bool operator== (const unsigned int n, const std::complex< double > &z)
bool operator!= (const unsigned int n, const std::complex< double > &z)
std::complex< double > expm1 (const std::complex< double > &z)
std::complex< double > log1p (const std::complex< double > &z)
std::complex< double > log_Gamma (const std::complex< double > &z)
std::complex< double > sigma_l_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_Cl_eta_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_AS_calc (const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_CFa_calc (const bool is_it_normalized, const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > log_cut_constant_CFb_calc (const bool is_it_normalized, const int omega, const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > sin_chi_calc (const std::complex< double > &l, const std::complex< double > &eta)
std::complex< double > exp_I_omega_chi_calc (const int omega, const std::complex< double > &l, const std::complex< double > &eta)
Variables
const double precision = 1E-10
const double sqrt_precision = 1E-5
Macro Definition Documentation
#define SIGN (a) (((a) < 0) ? (-1) : (1))
Referenced by exp_I_omega_chi_calc(), and Coulomb_wave_functions::F_dF().
Function Documentation
std::complex<double> exp_I_omega_chi_calc (const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References sigma_l_calc(), SIGN, and sin_chi_calc().
std::complex<double> expm1 (const std::complex< double > & z)
References expm1().
Referenced by expm1(), log_cut_constant_AS_calc(), and log_cut_constant_CFa_calc().
double inf_norm (const std::complex< double > & z) inline
Referenced by ODE_integration::operator()().
bool isfinite (const std::complex< double > & z) inline
Referenced by Coulomb_wave_functions::F_dF(), Coulomb_wave_functions::G_dG(), Coulomb_wave_functions::H_dH(), Coulomb_wave_functions::H_dH_scaled(), and log_Gamma().
std::complex<double> log1p (const std::complex< double > & z)
References log1p().
Referenced by log1p(), log_cut_constant_AS_calc(), and log_cut_constant_CFa_calc().
std::complex<double> log_Cl_eta_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Gamma().
Referenced by log_cut_constant_CFa_calc(), log_cut_constant_CFb_calc(), and sin_chi_calc().
std::complex<double> log_cut_constant_AS_calc (const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References expm1(), and log1p().
std::complex<double> log_cut_constant_CFa_calc (const bool is_it_normalized, const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References expm1(), log1p(), and log_Cl_eta_calc().
std::complex<double> log_cut_constant_CFb_calc (const bool is_it_normalized, const int omega, const std::complex< double > & l, const std::complex< double > & eta)
References log_Cl_eta_calc().
std::complex<double> log_Gamma (const std::complex< double > & z)
References isfinite(), and log_Gamma().
Referenced by log_Cl_eta_calc(), log_Gamma(), and sigma_l_calc().
bool operator!= (const std::complex< double > & z, const int n) inline
bool operator!= (const int n, const std::complex< double > & z) inline
bool operator!= (const std::complex< double > & z, const unsigned int n) inline
bool operator!= (const unsigned int n, const std::complex< double > & z) inline
std::complex<double> operator* (const std::complex< double > & z, const int n) inline
std::complex<double> operator* (const int n, const std::complex< double > & z) inline
std::complex<double> operator* (const std::complex< double > & z, const unsigned int n) inline
std::complex<double> operator* (const unsigned int n, const std::complex< double > & z) inline
std::complex<double> operator+ (const std::complex< double > & z, const int n) inline
std::complex<double> operator+ (const int n, const std::complex< double > & z) inline
std::complex<double> operator+ (const std::complex< double > & z, const unsigned int n) inline
std::complex<double> operator+ (const unsigned int n, const std::complex< double > & z) inline
std::complex<double> operator- (const std::complex< double > & z, const int n) inline
std::complex<double> operator- (const int n, const std::complex< double > & z) inline
std::complex<double> operator- (const std::complex< double > & z, const unsigned int n) inline
std::complex<double> operator- (const unsigned int n, const std::complex< double > & z) inline
std::complex<double> operator/ (const std::complex< double > & z, const int n) inline
std::complex<double> operator/ (const int n, const std::complex< double > & z) inline
std::complex<double> operator/ (const std::complex< double > & z, const unsigned int n) inline
std::complex<double> operator/ (const unsigned int n, const std::complex< double > & z) inline
bool operator== (const std::complex< double > & z, const int n) inline
bool operator== (const int n, const std::complex< double > & z) inline
bool operator== (const std::complex< double > & z, const unsigned int n) inline
bool operator== (const unsigned int n, const std::complex< double > & z) inline
std::complex<double> sigma_l_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Gamma().
Referenced by exp_I_omega_chi_calc().
std::complex<double> sin_chi_calc (const std::complex< double > & l, const std::complex< double > & eta)
References log_Cl_eta_calc().
Referenced by exp_I_omega_chi_calc().
Variable Documentation
const double precision = 1E-10
Referenced by ODE_integration::operator()().
const double sqrt_precision = 1E-5
Referenced by Coulomb_wave_functions::F_dF(), Coulomb_wave_functions::G_dG(), Coulomb_wave_functions::H_dH(), and Coulomb_wave_functions::H_dH_scaled().