Sapphire: Module_CrossSection Namespace Reference
Module_CrossSection Namespace Reference
Classes
struct EntrancePairs
Typedefs
typedef struct Module_CrossSection::EntrancePairs EntrancePairs
Functions
void Go (int argc, char *argv[])
Top level function to call from main for the reaction Module.
void Run (const SapphireInput &input)
Function to perform cross section calculations on the basis of a SapphireInput object.
void RunSingleReaction (const SapphireInput &input)
Function to perform a single reaction cross section calculations on the basis of a SapphireInput object.
void RunSingleReaction (std::string reactionString)
Function to perform a single reaction cross section calculations on the basis of a reactionString with default parameters.
void readEntrancePairs (std::vector< EntrancePairs > &entrancePairs, std::string reactionFile)
Method to read in the Entrance Pairs given in the reactionFile.
void PrintEntrancePairs (std::vector< EntrancePairs > &entrancePairs)
method to print the Entrance Pairsto stdout
bool fexists (const char *filename)
Check wheter a string represents an actual file.
std::string massNumberStringFromString (std::string reactionString)
Get the massNumberString from the reactionString.
int massNumberIntFromString (std::string reactionString)
Get the massNumberInt from the reactionString.
std::string pTypeStringFromString (std::string reactionString)
Get the pTypeString from the reactionString.
int pTypeIntFromString (std::string reactionString)
Get a projectile integer from a projectile string.
std::string atomicNumberStringFromString (std::string reactionString)
Get the atomic number as string from reactionString.
int atomicNumberIntFromString (std::string reactionString)
Get the atomic number as int from reactionString.
void printHelp ()
Funtion to print out the help information for the reaction module.
void readEntrancePairs (std::vector< EntrancePairs > *entrancePairs, std::string reactionFile)
Typedef Documentation
EntrancePairs
typedef struct Module_CrossSection::EntrancePairs Module_CrossSection::EntrancePairs
Function Documentation
atomicNumberIntFromString()
int Module_CrossSection::atomicNumberIntFromString (std::string reactionString)
Get the atomic number as int from reactionString.
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the reactionString, e.g. 28 other wise returns 0.
References atomicNumberStringFromString(), and NuclearMass::FindZ().
Referenced by RunSingleReaction().
atomicNumberStringFromString()
std::string Module_CrossSection::atomicNumberStringFromString (std::string reactionString)
Get the atomic number as string from reactionString.
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the reactionString, e.g. Fe
References massNumberStringFromString().
Referenced by atomicNumberIntFromString(), and pTypeStringFromString().
fexists()
bool Module_CrossSection::fexists (const char * filename)
Check wheter a string represents an actual file.
Parameters
filename String with the supposedly path to a file.
Returns
True if the file exists; False if it doesn't.
Referenced by Go().
Go()
void Module_CrossSection::Go (int argc, char * argv[])
Top level function to call from main for the reaction Module.
Parameters
argc Number of cmd line parameters of Sapphire.
argv The array which contains the cmd line parameters of Sapphire.
At the beginning of the Go() method a clock is started for the measurement of the total calculation time.
It'll be checked, whether enough cmd line parameters are given, otherwise the printHelp() method is called.
If enough cmd line parameters are given, then it'll be checked if the inputFile given is an actual file.
If the inputFile can be found, a SapphireInput object is created, the inputFile will be printed out via SapphireInput::printInputFile() and the content will be read into the SapphireInput object via SapphireInput::ReadInputFile().
The next step is to test if a single reaction calculation, or a calculations for reactions given in a reactionFile need to be performed. If the reactionFile is a actual file, the calculation continues with Run(). If the reactionFile is not a regular file, then the calculations will be performed with RunSingleReaction(). This means, if both keywords are set, the reactionFile option will overwrite the reaction keyword.
If no regular inputFile is given in the first place, the code assumes that the cmd line parameter is a reactionString. In this case RunSingleReaction will be called by passing the cmd line parameter.
At the end of the Go() method, the clock is stopped and the total calculation time is printed to std::cout.
At the beginning of the Go() method a clock is started for the measurement of the total calculation time.
It'll be checked, whether enough cmd line parameters are given, otherwise the printHelp() method is called.
If enough cmd line parameters are given, then it'll be checked if the inputFile given is an actual file.
If the inputFile can be found, a SapphireInput object is created, the inputFile will be printed out via SapphireInput::printInputFile() and the content will be read into the SapphireInput object via SapphireInput::ReadInputFile().
The next step is to test if a single reaction calculation, or a calculations for reactions given in a reactionFile need to be performed. If the reactionFile is a actual file, the calculation continues with Run(). If the reactionFile is not a regular file, then the calculations will be performed with RunSingleReaction(). This means, if both keywords are set, the reactionFile option will overwrite the reaction keyword.
If no regular inputFile is given in the first place, the code assumes that the cmd line parameter is a reactionString. In this case RunSingleReaction will be called by passing the cmd line parameter.
At the end of the Go() method, the clock is stopped and the total calculation time is printed to std::cout.
References fexists(), printHelp(), SapphireInput::printIntputFile(), SapphireInput::printIntputParameters(), SapphireInput::Reaction(), SapphireInput::ReactionFile(), SapphireInput::ReadInputFile(), Run(), and RunSingleReaction().
Referenced by main().
massNumberIntFromString()
int Module_CrossSection::massNumberIntFromString (std::string reactionString)
Get the massNumberInt from the reactionString.
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the reactionString, e.g. 60, if successful. Otherwise returns 0.
References massNumberStringFromString().
Referenced by RunSingleReaction().
massNumberStringFromString()
std::string Module_CrossSection::massNumberStringFromString (std::string reactionString)
Get the massNumberString from the reactionString.
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the reactionString, e.g. "60"
Referenced by atomicNumberStringFromString(), massNumberIntFromString(), and pTypeStringFromString().
PrintEntrancePairs()
void Module_CrossSection::PrintEntrancePairs (std::vector< EntrancePairs > & entrancePairs)
method to print the Entrance Pairsto stdout
printHelp()
void Module_CrossSection::printHelp ()
Funtion to print out the help information for the reaction module.
Referenced by Go().
pTypeIntFromString()
int Module_CrossSection::pTypeIntFromString (std::string reactionString)
Get a projectile integer from a projectile string.
Parameters
projectileString The part of the reactionString which defines the projectile.
Returns
Integer which represents the pType: 0 = gamma, 1 = neutron, 2 = proton, 3 = alpha.
Return "neutron" by default
Return "neutron" by default
References pTypeStringFromString().
Referenced by RunSingleReaction().
pTypeStringFromString()
std::string Module_CrossSection::pTypeStringFromString (std::string reactionString)
Get the pTypeString from the reactionString.
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The pType part of the reactionString, e.g. "p"
References atomicNumberStringFromString(), and massNumberStringFromString().
Referenced by pTypeIntFromString().
readEntrancePairs() [1/2]
void Module_CrossSection::readEntrancePairs (std::vector< EntrancePairs > & entrancePairs, std::string reactionFile)
Method to read in the Entrance Pairs given in the reactionFile.
Parameters
entrancePair A std::vector object which contains entrancePairs
reactionFile The file which contains a list of target charge and mass, as well as projectile type.
Referenced by Run().
readEntrancePairs() [2/2]
void Module_CrossSection::readEntrancePairs (std::vector< EntrancePairs > * entrancePairs, std::string reactionFile)
Run()
void Module_CrossSection::Run (const SapphireInput & input)
Function to perform cross section calculations on the basis of a SapphireInput object.
Parameters
input This is a SapphireInput object which should contain all parameters for the calculation of the cross section.
References SapphireInput::a_ExitStates(), SapphireInput::a_Formalism(), SapphireInput::CalcRates(), CrossSection::Calculate(), SapphireInput::CalculateGammaCutoff(), SapphireInput::DecayerMaxL(), SapphireInput::EnergyFile(), SapphireInput::g_CutoffEnergy(), SapphireInput::g_ExitStates(), SapphireInput::g_Formalism(), CrossSection::IsValid(), SapphireInput::n_ExitStates(), SapphireInput::n_Formalism(), SapphireInput::p_ExitStates(), SapphireInput::p_Formalism(), SapphireInput::PorterThomas_g(), SapphireInput::PorterThomas_p(), CrossSection::PrintCrossSections(), SapphireInput::ReactionFile(), readEntrancePairs(), SapphireInput::ResidualAlpha(), SapphireInput::ResidualGamma(), SapphireInput::ResidualNeutron(), SapphireInput::ResidualProton(), ParticleTransmissionFunc::SetAlphaFormalism(), CrossSection::SetCalculateGammaCutoff(), Decayer::SetCrossSection(), GammaTransmissionFunc::SetEGDRType(), TransitionRateFunc::SetGammaCutoffEnergy(), Decayer::SetMaxL(), ParticleTransmissionFunc::SetNeutronFormalism(), GammaTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetPorterThomas(), ParticleTransmissionFunc::SetProtonFormalism(), CrossSection::SetResidualAlpha(), CrossSection::SetResidualGamma(), CrossSection::SetResidualNeutron(), CrossSection::SetResidualProton(), and CrossSection::Z_.
Referenced by Go().
RunSingleReaction() [1/2]
void Module_CrossSection::RunSingleReaction (const SapphireInput & input)
Function to perform a single reaction cross section calculations on the basis of a SapphireInput object.
Parameters
input This is a SapphireInput object which should contain all parameters for the calculation of the cross section.
References SapphireInput::a_ExitStates(), atomicNumberIntFromString(), SapphireInput::CalcRates(), CrossSection::Calculate(), SapphireInput::EnergyFile(), SapphireInput::EntranceState(), SapphireInput::g_ExitStates(), CrossSection::IsValid(), massNumberIntFromString(), SapphireInput::n_ExitStates(), SapphireInput::p_ExitStates(), CrossSection::PrintCrossSections(), pTypeIntFromString(), and SapphireInput::Reaction().
Referenced by Go().
RunSingleReaction() [2/2]
void Module_CrossSection::RunSingleReaction (std::string reactionString)
Function to perform a single reaction cross section calculations on the basis of a reactionString with default parameters.
Parameters
reactionString This is a std::string object which contains the reaction in a format similar to "60Fe+p".
This method will invoke a cross section calculation for a reaction given as reactionString .
This method will invoke a cross section calculation for a reaction given as reactionString .
References atomicNumberIntFromString(), CrossSection::Calculate(), CrossSection::IsValid(), massNumberIntFromString(), CrossSection::PrintCrossSections(), and pTypeIntFromString().