Sapphire: SapphireInput Class Reference
SapphireInput Class Reference
#include <SapphireInput.h>
Public Member Functions
SapphireInput ()
Simple constructor.
SapphireInput (std::string fileName)
Constructor, directly passing the input file.
void Initialize ()
Initialize default values.
void Go (int argc, char *argv[])
Function which can be called from Sapphire.cpp to print out an example InputFile.
void ReadInputFile (std::string filename)
Read ini file and set the variables.
void printIntputFile (std::string filename)
Print InputFile to std::cout.
void printIntputParameters ()
Print Inputparameters to std::cout.
std::string massNumberStringFromReactionString (std::string reactionString)
Get the massNumberString from the reactionString.
int massNumberIntFromReactionString (std::string reactionString)
Get the massNumberInt from the reactionString.
std::string pTypeStringFromReactionString (std::string reactionString)
Get the pTypeString from the reactionString.
int pTypeIntFromReactionString (std::string reactionString)
Get a projectile integer from a projectile string.
std::string atomicNumberStringFromReactionString (std::string reactionString)
Get the atomic number as string from reactionString.
int atomicNumberIntFromReactionString (std::string reactionString)
Get the atomic number as int from reactionString.
std::string atomicNumberStringFromIsotopeString (std::string isotopeString)
Get the atomic number as string from isotopeString.
int atomicNumberIntFromIsotopeString (std::string isotopeString)
Get the atomic number as int from isotopeString.
std::string massNumberStringFromIsotopeString (std::string isotopeString)
Get the massNumberString from the isotopeString.
int massNumberIntFromIsotopeString (std::string isotopeString)
Get the massNumberInt from the isotopeString.
void CalcRates (bool x)
void CalcAverageWidth (bool x)
void ResidualGamma (bool x)
void ResidualNeutron (bool x)
void ResidualProton (bool x)
void ResidualAlpha (bool x)
void CalculateGammaCutoff (bool x)
void PorterThomas_g (bool x)
void PorterThomas_p (bool x)
void PrintTrans (bool x)
void PreEq (bool x)
void EntranceState (int x)
void g_ExitStates (int x)
void n_ExitStates (int x)
void p_ExitStates (int x)
void a_ExitStates (int x)
void g_Formalism (int x)
void n_Formalism (int x)
void p_Formalism (int x)
void a_Formalism (int x)
void Events (int x)
void ChunkSize (int x)
void Parity (int x)
void PType (int x)
void CompoundZ (int x)
void CompoundA (int x)
void GroundstatePi (int x)
void Suffix (int x)
void XsZ (int x)
void XsA (int x)
void DcZ (int x)
void DcA (int x)
void DecayerMaxL (double x)
void PreEqMaxL (double x)
void g_CutoffEnergy (double x)
void LowEnergy (double x)
void HighEnergy (double x)
void Spin (double x)
void GroundstateJ (double x)
void QValue (double x)
void EnergyFile (std::string x)
void Energies (std::string x)
void ReactionFile (std::string x)
void Reaction (std::string x)
void Isotope (std::string x)
void PreEqConf (std::string x)
void MassTable (std::string x)
void GdrParams (std::string x)
void LevelDir (std::string x)
void SpinFile (std::string x)
bool CalcRates () const
bool CalcAverageWidth () const
bool ResidualGamma () const
bool ResidualNeutron () const
bool ResidualProton () const
bool ResidualAlpha () const
bool CalculateGammaCutoff () const
bool PorterThomas_g () const
bool PorterThomas_p () const
bool PrintTrans () const
bool PreEq () const
int EntranceState () const
int g_ExitStates () const
int n_ExitStates () const
int p_ExitStates () const
int a_ExitStates () const
int g_Formalism () const
int n_Formalism () const
int p_Formalism () const
int a_Formalism () const
int Events () const
int ChunkSize () const
int Parity () const
int PType () const
int CompoundA () const
int CompoundZ () const
int GroundstatePi () const
int Suffix () const
int XsZ () const
int XsA () const
int DcZ () const
int DcA () const
double DecayerMaxL () const
double PreEqMaxL () const
double g_CutoffEnergy () const
double LowEnergy () const
double HighEnergy () const
double Spin () const
double GroundstateJ () const
double QValue () const
std::string EnergyFile () const
std::string Energies () const
std::string ReactionFile () const
std::string Reaction () const
std::string Isotope () const
std::string PreEqConf () const
std::string MassTable () const
std::string GdrParams () const
std::string LevelDir () const
std::string SpinFile () const
Private Attributes
bool calcRates
bool calcAverageWidth
bool residualGamma
bool residualNeutron
bool residualProton
bool residualAlpha
bool calculateGammaCutoff
bool porterThomas_g
bool porterThomas_p
bool printTrans
bool preEq
int entranceState
int g_exitStates
int n_exitStates
int p_exitStates
int a_exitStates
int n_formalism
int a_formalism
int p_formalism
int g_formalism
int events
int chunkSize
int parity
int pType
int compoundA
int compoundZ
int groundstatePi
int suffix
int xsZ
int xsA
int dcZ
int dcA
double decayerMaxL
double preEqMaxL
double g_cutoffEnergy
double lowEnergy
double highEnergy
double spin
double groundstateJ
double qValue
std::string energyFile
std::string reactionFile
std::string reaction
std::string energies
std::string isotope
std::string preEqConf
std::string massTable
std::string gdrParams
std::string levelDir
std::string spinFile
std::vector< int > exitStates
Constructor & Destructor Documentation
SapphireInput() [1/2]
SapphireInput::SapphireInput ()
References Initialize().
SapphireInput() [2/2]
SapphireInput::SapphireInput (std::string fileName)
Parameters
fileName Path to the inputFile Name
Member Function Documentation
a_ExitStates() [1/2]
void SapphireInput::a_ExitStates (int x) inline
<Setter for a_exitStates
References a_exitStates, and exitStates.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
a_ExitStates() [2/2]
int SapphireInput::a_ExitStates () const inline
Getter for a_exitStates
References a_exitStates.
Referenced by Initialize(), and printIntputParameters().
a_Formalism() [1/2]
void SapphireInput::a_Formalism (int x) inline
Setter for a_formalism
References a_formalism.
Referenced by Module_CrossSection::Run().
a_Formalism() [2/2]
int SapphireInput::a_Formalism () const inline
Getter for a_formalism
References a_formalism.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
atomicNumberIntFromIsotopeString()
int SapphireInput::atomicNumberIntFromIsotopeString (std::string isotopeString)
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the isotopeString, e.g. 28 other wise returns 0.
References atomicNumberStringFromIsotopeString(), and NuclearMass::FindZ().
Referenced by Isotope().
atomicNumberIntFromReactionString()
int SapphireInput::atomicNumberIntFromReactionString (std::string reactionString)
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the reactionString, e.g. 28 other wise returns 0.
References atomicNumberStringFromReactionString(), and NuclearMass::FindZ().
Referenced by Reaction().
atomicNumberStringFromIsotopeString()
std::string SapphireInput::atomicNumberStringFromIsotopeString (std::string isotopeString)
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the isotopeString, e.g. Fe
References massNumberStringFromIsotopeString().
Referenced by atomicNumberIntFromIsotopeString().
atomicNumberStringFromReactionString()
std::string SapphireInput::atomicNumberStringFromReactionString (std::string reactionString)
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The atomic number part of the reactionString, e.g. Fe
References massNumberStringFromReactionString().
Referenced by atomicNumberIntFromReactionString(), and pTypeStringFromReactionString().
CalcAverageWidth() [1/2]
void SapphireInput::CalcAverageWidth (bool x) inline
Setter for bool calcAverageWidth
References calcAverageWidth.
CalcAverageWidth() [2/2]
bool SapphireInput::CalcAverageWidth () const inline
Getter for calcAverageWidth
References calcAverageWidth.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
CalcRates() [1/2]
void SapphireInput::CalcRates (bool x) inline
Setter for bool calcRates
References calcRates.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
CalcRates() [2/2]
bool SapphireInput::CalcRates () const inline
Getter for calcrates
References calcRates.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
CalculateGammaCutoff() [1/2]
void SapphireInput::CalculateGammaCutoff (bool x) inline
Setter for bool calculateGammaCutoff
References calculateGammaCutoff.
Referenced by Module_CrossSection::Run().
CalculateGammaCutoff() [2/2]
bool SapphireInput::CalculateGammaCutoff () const inline
Getter for calculateGammaCutoff
References calculateGammaCutoff.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ChunkSize() [1/2]
void SapphireInput::ChunkSize (int x) inline
Setter for chunkSize
References chunkSize.
Referenced by Module_Decayer::Run().
ChunkSize() [2/2]
int SapphireInput::ChunkSize () const inline
Getter for chunkSize
References chunkSize.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
CompoundA() [1/2]
void SapphireInput::CompoundA (int x) inline
Setter for compoundA
References compoundA.
CompoundA() [2/2]
int SapphireInput::CompoundA () const inline
Getter for compoundA
References compoundA.
CompoundZ() [1/2]
void SapphireInput::CompoundZ (int x) inline
Setter for compoundZ
References compoundZ.
CompoundZ() [2/2]
int SapphireInput::CompoundZ () const inline
Getter for compoundZ
References compoundZ.
DcA() [1/2]
void SapphireInput::DcA (int x) inline
Setter for dcA
References dcA.
DcA() [2/2]
int SapphireInput::DcA () const inline
Getter for dcA
References dcA.
Referenced by Isotope().
DcZ() [1/2]
void SapphireInput::DcZ (int x) inline
Setter for dcZ
References dcZ.
DcZ() [2/2]
int SapphireInput::DcZ () const inline
Getter for dcZ
References dcZ.
Referenced by Isotope().
DecayerMaxL() [1/2]
void SapphireInput::DecayerMaxL (double x) inline
Setter for decayerMaxL
References decayerMaxL.
Referenced by Module_CrossSection::Run().
DecayerMaxL() [2/2]
double SapphireInput::DecayerMaxL () const inline
Getter for decayerMaxL
References decayerMaxL.
Referenced by Initialize().
Energies() [1/2]
void SapphireInput::Energies (std::string x) inline
Setter for string energies
References energies.
Energies() [2/2]
std::string SapphireInput::Energies () const inline
Getter for energies
References energies.
Referenced by ReadInputFile().
EnergyFile() [1/2]
void SapphireInput::EnergyFile (std::string x) inline
Setter for string energyFile
References energyFile.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
EnergyFile() [2/2]
std::string SapphireInput::EnergyFile () const inline
Getter for energyFile
References energyFile.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
EntranceState() [1/2]
void SapphireInput::EntranceState (int x) inline
Setter for entranceState
References entranceState.
Referenced by Module_CrossSection::RunSingleReaction().
EntranceState() [2/2]
int SapphireInput::EntranceState () const inline
Getter for entranceState
References entranceState.
Referenced by Initialize(), and printIntputParameters().
Events() [1/2]
void SapphireInput::Events (int x) inline
Setter for events
References events.
Referenced by Module_Decayer::Run().
Events() [2/2]
int SapphireInput::Events () const inline
Getter for events
References events.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
g_CutoffEnergy() [1/2]
void SapphireInput::g_CutoffEnergy (double x) inline
Setter for g_CutoffEnergy
References g_cutoffEnergy.
Referenced by Module_CrossSection::Run().
g_CutoffEnergy() [2/2]
double SapphireInput::g_CutoffEnergy () const inline
Getter for g_CutoffEnergy
References g_cutoffEnergy.
Referenced by Initialize().
g_ExitStates() [1/2]
void SapphireInput::g_ExitStates (int x) inline
<Setter for g_exitStates
References exitStates, and g_exitStates.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
g_ExitStates() [2/2]
int SapphireInput::g_ExitStates () const inline
Getter for g_exitStates
References g_exitStates.
Referenced by Initialize(), and printIntputParameters().
g_Formalism() [1/2]
void SapphireInput::g_Formalism (int x) inline
Setter for g_formalism
References g_formalism.
Referenced by Module_CrossSection::Run().
g_Formalism() [2/2]
int SapphireInput::g_Formalism () const inline
Getter for g_formalism
References g_formalism.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
GdrParams() [1/2]
void SapphireInput::GdrParams (std::string x) inline
Setter for string module
References gdrParams.
GdrParams() [2/2]
std::string SapphireInput::GdrParams () const inline
Getter for gdrParams
References gdrParams.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
Go()
void SapphireInput::Go (int argc, char * argv[])
References printIntputParameters().
Referenced by main().
GroundstateJ() [1/2]
void SapphireInput::GroundstateJ (double x) inline
Setter for groundstateJ
References groundstateJ.
GroundstateJ() [2/2]
double SapphireInput::GroundstateJ () const inline
Getter for groundstateJ
References groundstateJ.
GroundstatePi() [1/2]
void SapphireInput::GroundstatePi (int x) inline
Setter for groundstatePi
References groundstatePi.
GroundstatePi() [2/2]
int SapphireInput::GroundstatePi () const inline
Getter for groundstatePi
References groundstatePi.
HighEnergy() [1/2]
void SapphireInput::HighEnergy (double x) inline
Setter for highEnergy
References highEnergy.
Referenced by Module_Decayer::Run().
HighEnergy() [2/2]
double SapphireInput::HighEnergy () const inline
Getter for highEnergy
References highEnergy.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
Initialize()
void SapphireInput::Initialize ()
Setting default configurations for the SapphireInput class.
References a_ExitStates(), a_Formalism(), CalcAverageWidth(), CalcRates(), CalculateGammaCutoff(), ChunkSize(), DecayerMaxL(), EnergyFile(), EntranceState(), Events(), exitStates, g_CutoffEnergy(), g_ExitStates(), g_Formalism(), GdrParams(), HighEnergy(), Isotope(), LevelDir(), LowEnergy(), MassTable(), n_ExitStates(), n_Formalism(), p_ExitStates(), p_Formalism(), Parity(), PorterThomas_g(), PorterThomas_p(), PreEq(), PreEqConf(), PreEqMaxL(), Reaction(), ReactionFile(), ResidualAlpha(), ResidualGamma(), ResidualNeutron(), ResidualProton(), sourceDirectory(), Spin(), and SpinFile().
Referenced by SapphireInput().
Isotope() [1/2]
void SapphireInput::Isotope (std::string x) inline
<Setter for isotope
References atomicNumberIntFromIsotopeString(), DcA(), DcZ(), isotope, and massNumberIntFromIsotopeString().
Referenced by Module_Decayer::Run().
Isotope() [2/2]
std::string SapphireInput::Isotope () const inline
Getter for isotope
References isotope.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
LevelDir() [1/2]
void SapphireInput::LevelDir (std::string x) inline
Setter for string module
References levelDir.
LevelDir() [2/2]
std::string SapphireInput::LevelDir () const inline
Getter for levelDir
References levelDir.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
LowEnergy() [1/2]
void SapphireInput::LowEnergy (double x) inline
Setter for lowEnergy
References lowEnergy.
Referenced by Module_Decayer::Run().
LowEnergy() [2/2]
double SapphireInput::LowEnergy () const inline
Getter for lowEnergy
References lowEnergy.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
massNumberIntFromIsotopeString()
int SapphireInput::massNumberIntFromIsotopeString (std::string isotopeString)
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the isotopeString, e.g. 60, if successful. Otherwise returns 0.
References massNumberStringFromIsotopeString().
Referenced by Isotope().
massNumberIntFromReactionString()
int SapphireInput::massNumberIntFromReactionString (std::string reactionString)
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the reactionString, e.g. 60, if successful. Otherwise returns 0.
References massNumberStringFromReactionString().
Referenced by Reaction().
massNumberStringFromIsotopeString()
std::string SapphireInput::massNumberStringFromIsotopeString (std::string isotopeString)
Parameters
isotopeString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the isotopeString, e.g. "60"
Referenced by atomicNumberStringFromIsotopeString(), and massNumberIntFromIsotopeString().
massNumberStringFromReactionString()
std::string SapphireInput::massNumberStringFromReactionString (std::string reactionString)
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The mass number part of the reactionString, e.g. "60"
Referenced by atomicNumberStringFromReactionString(), massNumberIntFromReactionString(), and pTypeStringFromReactionString().
MassTable() [1/2]
void SapphireInput::MassTable (std::string x) inline
Setter for string module
References massTable.
MassTable() [2/2]
std::string SapphireInput::MassTable () const inline
Getter for massTable
References massTable.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
n_ExitStates() [1/2]
void SapphireInput::n_ExitStates (int x) inline
<Setter for n_exitStates
References exitStates, and n_exitStates.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
n_ExitStates() [2/2]
int SapphireInput::n_ExitStates () const inline
Getter for n_exitStates
References n_exitStates.
Referenced by Initialize(), and printIntputParameters().
n_Formalism() [1/2]
void SapphireInput::n_Formalism (int x) inline
Setter for n_formalism
References n_formalism.
Referenced by Module_CrossSection::Run().
n_Formalism() [2/2]
int SapphireInput::n_Formalism () const inline
Getter for n_formalism
References n_formalism.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
p_ExitStates() [1/2]
void SapphireInput::p_ExitStates (int x) inline
<Setter for p_exitStates
References exitStates, and p_exitStates.
Referenced by Module_CrossSection::Run(), and Module_CrossSection::RunSingleReaction().
p_ExitStates() [2/2]
int SapphireInput::p_ExitStates () const inline
Getter for p_exitStates
References p_exitStates.
Referenced by Initialize(), and printIntputParameters().
p_Formalism() [1/2]
void SapphireInput::p_Formalism (int x) inline
Setter for p_formalism
References p_formalism.
Referenced by Module_CrossSection::Run().
p_Formalism() [2/2]
int SapphireInput::p_Formalism () const inline
Getter for p_formalism
References p_formalism.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
Parity() [1/2]
void SapphireInput::Parity (int x) inline
Setter for parity
References parity.
Referenced by Module_Decayer::Run().
Parity() [2/2]
int SapphireInput::Parity () const inline
Getter for parity
References parity.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
PorterThomas_g() [1/2]
void SapphireInput::PorterThomas_g (bool x) inline
Setter for bool porterThomas_g
References porterThomas_g.
Referenced by Module_CrossSection::Run().
PorterThomas_g() [2/2]
bool SapphireInput::PorterThomas_g () const inline
Getter for bool porterThomas_g
References porterThomas_g.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
PorterThomas_p() [1/2]
void SapphireInput::PorterThomas_p (bool x) inline
Setter for bool porterThomas_p
References porterThomas_p.
Referenced by Module_CrossSection::Run().
PorterThomas_p() [2/2]
bool SapphireInput::PorterThomas_p () const inline
Getter for bool porterThomas_p
References porterThomas_p.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
PreEq() [1/2]
void SapphireInput::PreEq (bool x) inline
Setter for bool preEq
References preEq.
Referenced by Module_Decayer::Run().
PreEq() [2/2]
bool SapphireInput::PreEq () const inline
Getter for bool printTrans Getter for bool preEq
References preEq.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
PreEqConf() [1/2]
void SapphireInput::PreEqConf (std::string x) inline
Setter for preEqConf
References preEqConf.
PreEqConf() [2/2]
std::string SapphireInput::PreEqConf () const inline
Getter for preEqConf
References preEqConf.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
PreEqMaxL() [1/2]
void SapphireInput::PreEqMaxL (double x) inline
Setter for preEqMaxL
References preEqMaxL.
PreEqMaxL() [2/2]
double SapphireInput::PreEqMaxL () const inline
Getter for preEqMaxL
References preEqMaxL.
Referenced by Initialize().
printIntputFile()
void SapphireInput::printIntputFile (std::string filename)
Parameters
filename File name of the ini-File
Printing the inputfile as read by Sapphire. The InputFile is read in the same way here as for reading the inputFile. So, if something is off with the input, one can possibly see it from the output of this function.
Referenced by Module_Decayer::Go(), and Module_CrossSection::Go().
printIntputParameters()
void SapphireInput::printIntputParameters ()
This function prints out the current status of the input parameters, in a way, which can be used as input file template for other calculations. In comparison to a given input file, it can be double-checked if the parameters have been set as intended.
References a_ExitStates(), a_Formalism(), CalcAverageWidth(), CalcRates(), CalculateGammaCutoff(), ChunkSize(), EnergyFile(), EntranceState(), Events(), g_ExitStates(), g_Formalism(), GdrParams(), HighEnergy(), Isotope(), LevelDir(), LowEnergy(), MassTable(), n_ExitStates(), n_Formalism(), p_ExitStates(), p_Formalism(), Parity(), PorterThomas_g(), PorterThomas_p(), PreEq(), PreEqConf(), Reaction(), ReactionFile(), ResidualAlpha(), ResidualGamma(), ResidualNeutron(), ResidualProton(), Spin(), SpinFile(), and Suffix().
Referenced by Module_Decayer::Go(), Module_CrossSection::Go(), and Go().
PrintTrans() [1/2]
void SapphireInput::PrintTrans (bool x) inline
Setter for bool printTrans
References printTrans.
PrintTrans() [2/2]
bool SapphireInput::PrintTrans () const inline
References printTrans.
PType() [1/2]
void SapphireInput::PType (int x) inline
Setter for pType
References pType.
PType() [2/2]
int SapphireInput::PType () const inline
Getter for pType
References pType.
Referenced by Reaction().
pTypeIntFromReactionString()
int SapphireInput::pTypeIntFromReactionString (std::string reactionString)
Parameters
projectileString The part of the reactionString which defines the projectile.
Returns
Integer which represents the pType: 0 = gamma, 1 = neutron, 2 = proton, 3 = alpha.
Return "neutron" by default
References pTypeStringFromReactionString().
Referenced by Reaction().
pTypeStringFromReactionString()
std::string SapphireInput::pTypeStringFromReactionString (std::string reactionString)
Parameters
reactionString A string from the cmd line which represents the reaction, e.g., 60Fe+p
Returns
The pType part of the reactionString, e.g. "p"
References atomicNumberStringFromReactionString(), and massNumberStringFromReactionString().
Referenced by pTypeIntFromReactionString().
QValue() [1/2]
void SapphireInput::QValue (double x) inline
Setter for qValue
References qValue.
QValue() [2/2]
double SapphireInput::QValue () const inline
Getter for qValue
References qValue.
Reaction() [1/2]
void SapphireInput::Reaction (std::string x) inline
<Setter for reaction
References atomicNumberIntFromReactionString(), massNumberIntFromReactionString(), PType(), pTypeIntFromReactionString(), reaction, XsA(), and XsZ().
Referenced by Module_CrossSection::Go(), and Module_CrossSection::RunSingleReaction().
Reaction() [2/2]
std::string SapphireInput::Reaction () const inline
Getter for reaction
References reaction.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ReactionFile() [1/2]
void SapphireInput::ReactionFile (std::string x) inline
Setter for string reactionFile
References reactionFile.
Referenced by Module_CrossSection::Go(), and Module_CrossSection::Run().
ReactionFile() [2/2]
std::string SapphireInput::ReactionFile () const inline
Getter for reactionFile
References reactionFile.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ReadInputFile()
void SapphireInput::ReadInputFile (std::string filename)
Parameters
filename File name of the ini-File
References a_Formalism(), CalcAverageWidth(), CalcRates(), CalculateGammaCutoff(), ChunkSize(), Energies(), EnergyFile(), Events(), g_Formalism(), GdrParams(), HighEnergy(), Isotope(), LevelDir(), LowEnergy(), MassTable(), n_Formalism(), p_Formalism(), Parity(), PorterThomas_g(), PorterThomas_p(), PreEq(), PreEqConf(), Reaction(), ReactionFile(), ResidualAlpha(), ResidualGamma(), ResidualNeutron(), ResidualProton(), Spin(), SpinFile(), and Suffix().
Referenced by Module_Decayer::Go(), and Module_CrossSection::Go().
ResidualAlpha() [1/2]
void SapphireInput::ResidualAlpha (bool x) inline
Setter for bool residualAlpha
References residualAlpha.
Referenced by Module_CrossSection::Run().
ResidualAlpha() [2/2]
bool SapphireInput::ResidualAlpha () const inline
Getter for residualAlpha
References residualAlpha.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ResidualGamma() [1/2]
void SapphireInput::ResidualGamma (bool x) inline
Setter for bool residualGamma
References residualGamma.
Referenced by Module_CrossSection::Run().
ResidualGamma() [2/2]
bool SapphireInput::ResidualGamma () const inline
Getter for residualGamma
References residualGamma.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ResidualNeutron() [1/2]
void SapphireInput::ResidualNeutron (bool x) inline
Setter for bool residualNeutron
References residualNeutron.
Referenced by Module_CrossSection::Run().
ResidualNeutron() [2/2]
bool SapphireInput::ResidualNeutron () const inline
Getter for residualNeutron
References residualNeutron.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
ResidualProton() [1/2]
void SapphireInput::ResidualProton (bool x) inline
Setter for bool residualProton
References residualProton.
Referenced by Module_CrossSection::Run().
ResidualProton() [2/2]
bool SapphireInput::ResidualProton () const inline
Getter for residualProton
References residualProton.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
Spin() [1/2]
void SapphireInput::Spin (double x) inline
Setter for spin
References spin.
Referenced by Module_Decayer::Run().
Spin() [2/2]
double SapphireInput::Spin () const inline
Getter for spin
References spin.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
SpinFile() [1/2]
void SapphireInput::SpinFile (std::string x) inline
Setter for string module
References spinFile.
SpinFile() [2/2]
std::string SapphireInput::SpinFile () const inline
Getter for spinFile
References spinFile.
Referenced by Initialize(), printIntputParameters(), and ReadInputFile().
Suffix() [1/2]
void SapphireInput::Suffix (int x) inline
Setter for string module
References suffix.
Referenced by Module_Decayer::Run().
Suffix() [2/2]
int SapphireInput::Suffix () const inline
Getter for suffix
References suffix.
Referenced by printIntputParameters(), and ReadInputFile().
XsA() [1/2]
void SapphireInput::XsA (int x) inline
Setter for xsA
References xsA.
XsA() [2/2]
int SapphireInput::XsA () const inline
Getter for xsA
References xsA.
Referenced by Reaction().
XsZ() [1/2]
void SapphireInput::XsZ (int x) inline
Setter for xsZ
References xsZ.
XsZ() [2/2]
int SapphireInput::XsZ () const inline
Getter for xsZ
References xsZ.
Referenced by Reaction().
Member Data Documentation
a_exitStates
int SapphireInput::a_exitStates private
Int for the number of exitStates for alpha residual
Referenced by a_ExitStates().
a_formalism
int SapphireInput::a_formalism private
Choose alpha OMP
Referenced by a_Formalism().
calcAverageWidth
bool SapphireInput::calcAverageWidth private
Bool if average widths should be calculated
Referenced by CalcAverageWidth().
calcRates
bool SapphireInput::calcRates private
Bool if rates should be calculated
Referenced by CalcRates().
calculateGammaCutoff
bool SapphireInput::calculateGammaCutoff private
Bool if the GammaCutoffenergy should be calculated or not.
Referenced by CalculateGammaCutoff().
chunkSize
int SapphireInput::chunkSize private
Portion of the total numbers of decays which is calculated at once.
Referenced by ChunkSize().
compoundA
int SapphireInput::compoundA private
Int for the mass of the compound nuclei
Referenced by CompoundA().
compoundZ
int SapphireInput::compoundZ private
Int for the charge of the compound nuclei
Referenced by CompoundZ().
dcA
int SapphireInput::dcA private
Integer for the charge number of the isotope in decayer module
Referenced by DcA().
dcZ
int SapphireInput::dcZ private
Integer for the mass number of the isotope in reaction module
Referenced by DcZ().
decayerMaxL
double SapphireInput::decayerMaxL private
Integer for the mass number of the isotope in decayer module Maximum l-value for the decayer
Referenced by DecayerMaxL().
energies
std::string SapphireInput::energies private
String for reaction
Referenced by Energies().
energyFile
std::string SapphireInput::energyFile private
String with the path to the energyFile
Referenced by EnergyFile().
entranceState
int SapphireInput::entranceState private
Int for the number of level, which should be the entrance State
Referenced by EntranceState().
events
int SapphireInput::events private
Number of decays
Referenced by Events().
exitStates
std::vector<int> SapphireInput::exitStates private
Vector of integer for the number of exitStates
Referenced by a_ExitStates(), g_ExitStates(), Initialize(), n_ExitStates(), and p_ExitStates().
g_cutoffEnergy
double SapphireInput::g_cutoffEnergy private
Double for the Gamma Cutoff energy
Referenced by g_CutoffEnergy().
g_exitStates
int SapphireInput::g_exitStates private
Int for the number of exitStates for gamma residual
Referenced by g_ExitStates().
g_formalism
int SapphireInput::g_formalism private
Choose gamma strength function
Referenced by g_Formalism().
gdrParams
std::string SapphireInput::gdrParams private
String for the path to the GDR parameter file
Referenced by GdrParams().
groundstateJ
double SapphireInput::groundstateJ private
Spin of the groundstate
Referenced by GroundstateJ().
groundstatePi
int SapphireInput::groundstatePi private
Int for the parity of the groundstate
Referenced by GroundstatePi().
highEnergy
double SapphireInput::highEnergy private
higher limit for initial energy
Referenced by HighEnergy().
isotope
std::string SapphireInput::isotope private
String for the istope for the decay simulation
Referenced by Isotope().
levelDir
std::string SapphireInput::levelDir private
String for the path to the levels directory
Referenced by LevelDir().
lowEnergy
double SapphireInput::lowEnergy private
lower limit for initial energy
Referenced by LowEnergy().
massTable
std::string SapphireInput::massTable private
String for the path to the mass tables
Referenced by MassTable().
n_exitStates
int SapphireInput::n_exitStates private
Int for the number of exitStates for neutron residual
Referenced by n_ExitStates().
n_formalism
int SapphireInput::n_formalism private
Choose neutron OMP
Referenced by n_Formalism().
p_exitStates
int SapphireInput::p_exitStates private
Int for the number of exitStates for proton residual
Referenced by p_ExitStates().
p_formalism
int SapphireInput::p_formalism private
Choose proton OMP
Referenced by p_Formalism().
parity
int SapphireInput::parity private
Parity of the high energy resonance
Referenced by Parity().
porterThomas_g
bool SapphireInput::porterThomas_g private
Bool for PorterThomas usage gamma
Referenced by PorterThomas_g().
porterThomas_p
bool SapphireInput::porterThomas_p private
Bool for PorterThomas usage particle
Referenced by PorterThomas_p().
preEq
bool SapphireInput::preEq private
Bool for preEq.
Referenced by PreEq().
preEqConf
std::string SapphireInput::preEqConf private
Preequillibrium exciton configuration of the initial state (pp,ph,np,nh)
Referenced by PreEqConf().
preEqMaxL
double SapphireInput::preEqMaxL private
Maximum l-value for the preEq
Referenced by PreEqMaxL().
printTrans
bool SapphireInput::printTrans private
Bool if transmission should be printed
Referenced by PrintTrans().
pType
int SapphireInput::pType private
Type of projectile
Referenced by PType().
qValue
double SapphireInput::qValue private
double for the qvalue of the reaction
Referenced by QValue().
reaction
std::string SapphireInput::reaction private
String for reaction
Referenced by Reaction().
reactionFile
std::string SapphireInput::reactionFile private
String with the path to the reactionFile
Referenced by ReactionFile().
residualAlpha
bool SapphireInput::residualAlpha private
Bool if residual cross section for alpha should be calculated
Referenced by ResidualAlpha().
residualGamma
bool SapphireInput::residualGamma private
Bool if residual cross section for gamma should be calculated
Referenced by ResidualGamma().
residualNeutron
bool SapphireInput::residualNeutron private
Bool if residual cross section for neutron should be calculated
Referenced by ResidualNeutron().
residualProton
bool SapphireInput::residualProton private
Bool if residual cross section for proton should be calculated
Referenced by ResidualProton().
spin
double SapphireInput::spin private
Spin of the decaying resonance
Referenced by Spin().
spinFile
std::string SapphireInput::spinFile private
String for the path tot the spinFile
Referenced by SpinFile().
suffix
int SapphireInput::suffix private
Suffix for output
Referenced by Suffix().
xsA
int SapphireInput::xsA private
Integer for the charge number of the isotope in reaction module
Referenced by XsA().
xsZ
int SapphireInput::xsZ private
Referenced by XsZ().
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/SapphireInput.h
/home/pscholz/SAPPHIRE/src/SapphireInput.cpp