Sapphire: DecayController Class Reference
DecayController Class Reference
#include <DecayController.h>
Public Member Functions
DecayController (int Z, int A, double jInitial, int piInitial, double energy, int initialNeutronNumber=-1, int initialNeutronHoleNumber=-1, int initialProtonNumber=-1, int initialProtonHoleNumber=-1)
bool Decay (double &, double &, double &, double &, double &, double &, double &, double &)
std::vector< DecayProduct > DecayProducts () const
void PrintDecays ()
Constructor & Destructor Documentation
DecayController::DecayController (int Z, int A, double jInitial, int piInitial, double energy, int initialNeutronNumber = -1, int initialNeutronHoleNumber = -1, int initialProtonNumber = -1, int initialProtonHoleNumber = -1) inline
Member Function Documentation
bool DecayController::Decay (double & neutronEntrance, double & protonEntrance, double & alphaEntrance, double & gammaEntrance, double & neutronTotalWidth, double & protonTotalWidth, double & alphaTotalWidth, double & gammaTotalWidth)
References Decayer::AlphaEntranceWidth(), Decayer::AlphaTotalWidth(), Decayer::Decay(), PreEqDecayer::Decay(), Decayer::GammaEntranceWidth(), Decayer::GammaTotalWidth(), Decayer::NeutronEntranceWidth(), Decayer::NeutronTotalWidth(), Decayer::ProtonEntranceWidth(), and Decayer::ProtonTotalWidth().
Referenced by main().
std::vector<DecayProduct> DecayController::DecayProducts () const inline
Referenced by main().
void DecayController::PrintDecays ()
Referenced by main().
The documentation for this class was generated from the following files:
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/include/DecayController.h
/afs/crc.nd.edu/user/p/pscholz/Private/sapphire-devel/src/DecayController.cpp