Sapphire: ParticleHoleLevelDensity Class Reference
ParticleHoleLevelDensity Class Reference
#include <ParticleHoleLevelDensity.h>
Public Member Functions
ParticleHoleLevelDensity (int, int, double, int, int, int, int)
double operator() (double energy, bool correct=true, bool spin=false)
double PauliCorrection (int, int, int, int)
double PairingCorrection (double energy)
double gNu () const
double gPi () const
double FiniteDepth (double)
Private Attributes
bool invalid_
int totalExcitonNumber_
int totalHoleNumber_
int incident_
int A_
int Z_
double separationEnergy_
double preFactor_
double pauliCorrection_
double pairingEnergy_
double nCritical_
double spinFactor_
double gPi_
double gNu_
Constructor & Destructor Documentation
ParticleHoleLevelDensity()
ParticleHoleLevelDensity::ParticleHoleLevelDensity (int Z, int A, double J, int neutronNumber, int neutronHoleNumber, int protonNumber, int protonHoleNumber)
References gNu_, gPi_, incident_, invalid_, nCritical_, pairingEnergy_, PauliCorrection(), pauliCorrection_, preFactor_, NuclearMass::QValue(), separationEnergy_, spinFactor_, totalExcitonNumber_, and totalHoleNumber_.
Member Function Documentation
FiniteDepth()
double ParticleHoleLevelDensity::FiniteDepth (double energy)
References A_, incident_, separationEnergy_, totalExcitonNumber_, and totalHoleNumber_.
Referenced by gPi(), and operator()().
gNu()
double ParticleHoleLevelDensity::gNu () const inline
References gNu_.
Referenced by PreEqTransitionRateFunc::CalcNeutronPairProduction(), and PreEqTransitionRateFunc::CalcProtonPairProduction().
gPi()
double ParticleHoleLevelDensity::gPi () const inline
References FiniteDepth(), and gPi_.
Referenced by PreEqTransitionRateFunc::CalcNeutronPairProduction(), and PreEqTransitionRateFunc::CalcProtonPairProduction().
operator()()
double ParticleHoleLevelDensity::operator() (double energy, bool correct = true, bool spin = false)
References FiniteDepth(), invalid_, PairingCorrection(), pauliCorrection_, preFactor_, spinFactor_, and totalExcitonNumber_.
PairingCorrection()
double ParticleHoleLevelDensity::PairingCorrection (double energy)
References invalid_, nCritical_, pairingEnergy_, and totalExcitonNumber_.
Referenced by PreEqTransitionRateFunc::CalcNeutronPairConversion(), PreEqTransitionRateFunc::CalcNeutronPairProduction(), PreEqTransitionRateFunc::CalcProtonPairConversion(), PreEqTransitionRateFunc::CalcProtonPairProduction(), and operator()().
PauliCorrection()
double ParticleHoleLevelDensity::PauliCorrection (int neutronNumber, int neutronHoleNumber, int protonNumber, int protonHoleNumber)
References gNu_, gPi_, and invalid_.
Referenced by PreEqTransitionRateFunc::CalcNeutronPairConversion(), PreEqTransitionRateFunc::CalcNeutronPairProduction(), PreEqTransitionRateFunc::CalcProtonPairConversion(), PreEqTransitionRateFunc::CalcProtonPairProduction(), and ParticleHoleLevelDensity().
Member Data Documentation
A_
int ParticleHoleLevelDensity::A_ private
Referenced by FiniteDepth().
gNu_
double ParticleHoleLevelDensity::gNu_ private
Referenced by gNu(), ParticleHoleLevelDensity(), and PauliCorrection().
gPi_
double ParticleHoleLevelDensity::gPi_ private
Referenced by gPi(), ParticleHoleLevelDensity(), and PauliCorrection().
incident_
int ParticleHoleLevelDensity::incident_ private
Referenced by FiniteDepth(), and ParticleHoleLevelDensity().
invalid_
bool ParticleHoleLevelDensity::invalid_ private
Referenced by operator()(), PairingCorrection(), ParticleHoleLevelDensity(), and PauliCorrection().
nCritical_
double ParticleHoleLevelDensity::nCritical_ private
Referenced by PairingCorrection(), and ParticleHoleLevelDensity().
pairingEnergy_
double ParticleHoleLevelDensity::pairingEnergy_ private
Referenced by PairingCorrection(), and ParticleHoleLevelDensity().
pauliCorrection_
double ParticleHoleLevelDensity::pauliCorrection_ private
Referenced by operator()(), and ParticleHoleLevelDensity().
preFactor_
double ParticleHoleLevelDensity::preFactor_ private
Referenced by operator()(), and ParticleHoleLevelDensity().
separationEnergy_
double ParticleHoleLevelDensity::separationEnergy_ private
Referenced by FiniteDepth(), and ParticleHoleLevelDensity().
spinFactor_
double ParticleHoleLevelDensity::spinFactor_ private
Referenced by operator()(), and ParticleHoleLevelDensity().
totalExcitonNumber_
int ParticleHoleLevelDensity::totalExcitonNumber_ private
Referenced by FiniteDepth(), operator()(), PairingCorrection(), and ParticleHoleLevelDensity().
totalHoleNumber_
int ParticleHoleLevelDensity::totalHoleNumber_ private
Referenced by FiniteDepth(), and ParticleHoleLevelDensity().
Z_
int ParticleHoleLevelDensity::Z_ private
The documentation for this class was generated from the following files:
/home/pscholz/SAPPHIRE/include/ParticleHoleLevelDensity.h
/home/pscholz/SAPPHIRE/src/ParticleHoleLevelDensity.cpp